### ISSUE TITLE
"panel examples" command does not work

### ISSUE THREAD

**Issue by ceball** [pyviz/panel#109]
Following http://panel.pyviz.org/#usage, I couldn't get the examples:
```
$ panel --install-examples
usage: /home/ceball/mc3/envs/panel/bin/panel [-h] [-v] {html,info,json,png,sampledata,secret,serve,static,svg} ...
/home/ceball/mc3/envs/panel/bin/panel: error: unrecognized arguments: --install-examples
```

I was going to add pyct to make `panel examples` available (in common with other pyviz projects), but I'm not sure how I ought to do that, because there doesn't seem to be any existing argparse parser I can add to - bokeh's main() is  just called.

**Comment by jbednar** [comment]
@jlstevens is going to need to add argparse-based options anyway, so can you please set it up to be like all our other projects except that if a command doesn't match and it would otherwise show a usage message, instead it call's bokeh's main()?

**Comment by jbednar** [comment]
@jlstevens, it looks like our instructions still don't match what panel currently does, and everything will be more consistent if we change what panel does rather than the instructions...

**Comment by jlstevens** [comment]
It should now be working, though I think the command is just `panel examples`. Closing.
