### ISSUE TITLE
Feature Request: support param.DataFrame

### ISSUE THREAD

**Issue by wabu** [pyviz/panel#113]
I'd like to have a larger tabular configuration inside a Dashboard, so `param.DataFrame` seems to match my requirements quite well, but currently panel does not support showing DataFrame params:

```python
import param
import panel as pn
import pandas as pd

pn.extension()

class Config(param.Parameterized):
    tabular = param.DataFrame(pd.DataFrame({'a': [1,2,3], 
                                            'b': ["foo", "bar", "baz"]}), 
                              columns={'a', 'b'})
    
pn.Pane(Config)
```

```
TypeError: 'DataFrame' objects are mutable, thus they cannot be hashed
```

I'm currently using `hv.Table(..).options(editable=True)` and an `Apply` Action as a work-around, 
but that break a clean design. 

As I'm not familiar with javascript it's hard for me to develop a feature like this myself.

**Comment by DancingQuanta** [comment]
HI @wabu, could you document your workaround please?

**Comment by wabu** [comment]
I now ended up using a bokeh `DataTable`, for which you can subscribe to change on the source:
```
source = bokeh.models.ColumnDataSource(pd.DataFrame(data).to_dict(orient='list'))
columns = [bokeh.models.TableColumn(field=name,
                                    title=name.replace('_', ' ').title(),
                                    editor=mk_edit(vals))
           for name, vals in data.items()]
table = bokeh.models.DataTable(source=source, 
                                 columns=columns, 
                                 editable=True)
```

**Comment by kcpevey** [comment]
Update: Currently, param.Dataframe can be rendered by wrapping a df in a panel, e.g. `pn.panel(df)`. However, that doesn't produce an editable dataframe.

**Comment by kcpevey** [comment]
Also note that the above workaround of transferring the df to a bokeh table doesn't provide a link to expose the table edits back to the python side.

**Comment by philippjfr** [comment]
Okay, I'll work on a DataFrame pane, with an ``interactive`` toggle which will allow switching between a raw html view and an editable bokeh table.
