### ISSUE TITLE
Overriding the names of widgets

### ISSUE THREAD

**Issue by ahuang11** [pyviz/panel#117]
I know it inherits from variable name and titlelizes, removing the underscore, but if I wanted a different, longer name, I don't want my code to be cluttered with a long variable name.

![image](https://user-images.githubusercontent.com/15331990/47317264-fb0a5280-d5fd-11e8-9dbb-02ef386f2409.png)

Philipp suggested `panel.Pane(Example.param, rename={'unbounded_float': 'My float variable'})`

**Comment by jbednar** [comment]
ParamBokeh provided [label_formatter=default_label_formatter](https://github.com/ioam/parambokeh/blob/master/parambokeh/__init__.py#L185), where
[default_label_formatter](https://github.com/ioam/parambokeh/blob/master/parambokeh/__init__.py#L97) provides a list of `overrides` that's equivalent to `rename` here.  That approach is more general, as it lets people provide their own mapping function or object, so I propose we just copy that from ParamBokeh.

**Comment by jbednar** [comment]
I suppose you would `import default_label_formatter as dlf` then supply an argument:

```
label_formatter=(dlf.instance(overrides = {'unbounded_float': 'My float variable'}))
```

or you can do it globally:

```
import default_label_formatter as dlf
dlf.overrides={'unbounded_float': 'My float variable'}
```

So it's general, but indeed it's awkward if this is something you want to do a lot.

**Comment by MHC03** [comment]
How would it be to extract the names of Parameter objects directly to derive the visualization titles. This would of course require `name` attributes for Parameter objects.  It would free me from variable names like `statistics_additional_label_randomization`.

**Comment by misolietavec** [comment]
In panel `0.3.1.post3+g13d40f0` I can set the overrides by:
```python
import panel as pn
...

pn.Param.label_formatter.capitalize=False
pn.Param.label_formatter.overrides={'ur':'(umin .. umax)', 'vr':'(vmin .. vmax)'}
```

**Comment by kcpevey** [comment]
>pn.Param.label_formatter.overrides={'ur':'(umin .. umax)', 'vr':'(vmin .. vmax)'}
  
I spent way too much time pulling my hair out over this before I came across this. Thanks!

**Comment by jbednar** [comment]
I do agree with @MHC03 that it would be nice to be able to declare formatted names for Parameters that are used for display when defined, instead of the attribute name.

**Comment by philippjfr** [comment]
Yes I think we discussed whether we should add a label directlt on parameters.

**Comment by kcpevey** [comment]
>add a label directly on parameters 
  
That was my first and second thought (e.g. I tried `name='foo'` and `label='foo'` on the param object.

**Comment by jbednar** [comment]
On balance, I think `label` is probably clearer than `name`, so that we can easily talk about the Parameter's name (the attribute name) separately from its label (this new text).

**Comment by philippjfr** [comment]
In the next param release there parameters will accept a label keyword so I'll close.
