### ISSUE TITLE
assign function to Button widget 

### ISSUE THREAD

**Issue by rr5577** [pyviz/panel#122]
I´m probably missing something really obvious (sorry), but how can i get the button widget to execute a function?

**Comment by gregmuellegger** [comment]
It is a little hidden behind the `watch` method:

```
def on_click(event):
    do_something()

button = panel.widgets.Button(name='Click me')
button.param.watch(on_click, 'clicks')
```

Hope this helps.

**Comment by rr5577** [comment]
Thank you, much appreciated!
