### ISSUE TITLE
Supply compositional reprs

### ISSUE THREAD

**Issue by jlstevens** [pyviz/panel#125]
One issue that cropped up discussing #124 is that panel does not currently supply compositional reprs allowing you to see the structure of the object. These probably can't be fully declarative (i.e `eval`able reprs) but some representation of the composition would be very useful (the obvious example of such reprs are those I am familiar with in holoviews).

**Comment by jbednar** [comment]
The reprs in holoviews look a bit odd at first, but I really find them convenient for figuring out what's in the object and how to index into it.  E.g.:

```
:Layout
   .Scatter.I   :Scatter   [services]   (ridership)
   .Histogram.I :Histogram   [opened]   (Frequency)
```

In Panel, maybe the equivalent would be something like:

```
:Row  
   [0] :Column
       [0] :HTML Some text...
       [1] :PNG  50 x 100 filename
    [1] :Param 6 widgets
    [2] :HoloViews  Group.Label
```

Just brainstorming...


```

**Comment by philippjfr** [comment]
Now implemented something, any suggested improvements should get their own issue.
