### ISSUE TITLE
Errors in watch handlers are swallowed, and are hard to debug

### ISSUE THREAD

**Issue by gregmuellegger** [pyviz/panel#134]
I stumbled upon an issue that the watch handler for a param attribute is properly called, but swallows exceptions (when using panel inside a Jupyter Lab notebook). This makes it hard to see where a code errors, since there is no indication for where or what went wrong.

![image](https://user-images.githubusercontent.com/88278/47907346-5e607400-de8b-11e8-8a0e-281cf6cb0af4.png)

Is there a way make those errors bubble or to ease the debugging experience here?

**Comment by philippjfr** [comment]
The easiest way to debug currently is to look at your browser's web console:

![screen shot 2018-11-02 at 11 26 36 am](https://user-images.githubusercontent.com/1550771/47912991-53f5a880-de92-11e8-817a-57576a8a1617.png)

We've considered in the past to somehow let the error bubble up to user in a more obvious way but it's not quite clear how to do that.

**Comment by philippjfr** [comment]
This was added to the FAQ.
