### ISSUE TITLE
TextInput stuck when running heavy calculations on server

### ISSUE THREAD

**Issue by MHC03** [pyviz/panel#138]
When I am trying to run heavy calculations and change the value of the TextInput beforehand, the value change somehow seems to be stuck. I have prepared a small example:

```python
pn.extension()

def heavy_calculation():
    epos_indexed = epos[0:10_000_000]
    cropped_index = np.where((epos_indexed['dx'] >= -5) & (epos_indexed['dx'] <= 10) 
                              & (epos_indexed['dy'] >= -10) & epos_indexed['dy'] <= 15)[0]
    # print(list(cropped_index))
    cropped_epos = epos.iloc[list(cropped_index)]

class Test:
    
    def __init__(self):
        self.button = pn.widgets.Button(name='Click Me!')
        self.txt = pn.widgets.TextInput(name='Misused as Log:')
        self.button.param.watch(self._button_click, 'clicks')
        
    def _button_click(self, clicks):
        self.txt.value = 'Start heavy calculation...'
        heavy_calculation()
        self.txt.value = 'Heavy calculation finished.'
    
    def view(self):
        return pn.Column(self.button, self.txt)

Test().view()
```
When I run this on a jupyter notebook, there is no problem:

![jupyter_heavy_calc](https://user-images.githubusercontent.com/22367686/48063330-fbd9e180-e1c4-11e8-8cc0-542b700cd225.gif)

But when I deploy it using ` panel serve --show`, the first message on the TextInput widget does not appear:

![server_heavy_calculation](https://user-images.githubusercontent.com/22367686/48063408-3774ab80-e1c5-11e8-933f-c0e125d5c1fb.gif)

For deploying I have downloaded the notebook as a python file and edited `Test().view()` to `Test().view().server_doc()`.

epos is just a pandas DataFrame containing 36,000,000 elements.
I am not sure, whether this is a panel or bokeh problem.

**Comment by philippjfr** [comment]
Thanks for the report. I'll look into as a quick aside:

>For deploying I have downloaded the notebook as a python file and edited Test().show() to Test().show().server_doc().

This shouldn't be necessary, you can have the notebook work both in the notebook and on bokeh server by using ``Test().show().servable()``. That will render in a notebook **and** work when you use ``panel serve notebook.ipynb --show``.

**Comment by philippjfr** [comment]
Okay, so this is a pretty central part of how bokeh server works, changing a parameter value will schedule a so called ``next_tick_callback``, which won't be processed while the "heavy_calculation" is being processed. Ordinarily you could also schedule the calculation as a next_tick_callback and we could consider exposing that mechanism in an easy way. However it would of course be a lot nicer if we could somehow make the naive approach work, I'll have to read a bit more about tornado and bokeh server to see if that's feasible.

**Comment by MHC03** [comment]
Thank you very much for looking into all of the issues. For me personally either way is fine, if it is too hard to make it work the naive way, I can try with the `next_tick_callback.` (But I have to look into how this works)

**Comment by philippjfr** [comment]
@MHC03 So there's probably nothing we can do automatically, however you can do it by using the tornado IOLoop, in your example you'd do something like:

```
    def _button_click(self, clicks):
        self.txt.value = 'Start heavy calculation...'
        ioloop = tornado.ioloop.IOLoop.current()
        ioloop.add_callback(self._heavy_calculation)
        
    def _heavy_calculation(self):
        heavy_calculation()
        self.txt.value = 'Heavy calculation finished.'
```

**Comment by jbednar** [comment]
This code would be a bit less confusing if you changed your show() method to view(), to avoid confusion with Panel's .show() method.

**Comment by philippjfr** [comment]
>For me the above approach does not fully work, the second change to the textinput value does not occur. It is stuck with 'Start heavy calculation...'.

Yeah, it's not quite clear to me what's going on here, it's definitely not working right in this case but I've used it successfully in other examples.

**Comment by MHC03** [comment]
> 
> 
> This code would be a bit less confusing if you changed your show() method to view(), to avoid confusion with Panel's .show() method.

Changed it, maybe  @philippjfr can also edit his comment.

> 
> 
> Yeah, it's not quite clear to me what's going on here, it's definitely not working right in this case but I've used it successfully in other examples.

I will try some workaround with the ioloop callback for now. Thanks a lot for looking into this stuff.

**Comment by philippjfr** [comment]
>Thanks a lot for looking into this stuff.

No problem, I'm encountering the same issues so this is fairly high priority. Still searching for a better solution, but my knowledge of tornado is lacking a bit.
