### ISSUE TITLE
Tab names are taken from last child

### ISSUE THREAD

**Issue by MHC03** [pyviz/panel#148]
The names I give my tabs are ignored. Panel prefers to take the name 'bottom-up', it takes the name from the innermost widget in the tab for the tab. I would prefer a 'top-down' approach, where it takes the name of the first named child or preferably his own name.

Example:

```python
import panel as pn
pn.extension()

class Tabs:
    
    def __init__(self):
        self.first_tab = pn.Column(pn.widgets.TextInput(name='Test'))
        self.second_tab = pn.Column(pn.widgets.Button(), name='Second')
        self.third_tab = pn.Row(pn.widgets.Button(name='Third'))
        self.fourth_tab = pn.Row(pn.widgets.Button(name='Go'), name='Rowy')
        self.layout = pn.Tabs(('Main', self.first_tab), ('Second', self.second_tab), self.third_tab, 
                              ('Blub', self.fourth_tab))

Tabs().layout.servable()
```

![tab_names](https://user-images.githubusercontent.com/22367686/48418823-9bafe600-e756-11e8-8106-cf957cde35f4.gif)

**Comment by philippjfr** [comment]
This has also annoyed me and I'll push a fix shortly. However I don't think it should be inspecting the internals of a Row/Column to find a name so you'd have to move the ``name`` kwarg on your third tab onto the Row.
