### ISSUE TITLE
Strip out magics when using panel serve

### ISSUE THREAD

**Issue by jlstevens** [pyviz/panel#157]
In holoviews we have code that can strip magics out of notebooks (and convert some of the magics we control). Right now `panel serve` wraps `bokeh serve` in a simple way: it would be nice to hook into bokeh and add some useful notebook preprocessors.

**Comment by philippjfr** [comment]
This is now being implemented upstream in bokeh's ``NotebookHandler`` (in this PR https://github.com/bokeh/bokeh/pull/8539) so I'll close this issue.
