### ISSUE TITLE
Can pipelines output non param objects?

### ISSUE THREAD

**Issue by kcpevey** [pyviz/panel#160]
From the user guide:  
>declare a Parameter named c which will consume the output of the first stage
  
But what if I'd like the first stage to output an instantiated class object that isn't a param and possibly isn't a param.Parameterized class. Is that possible?  How would I declare that output in the second stage?

**Comment by kcpevey** [comment]
and can I just use:

```
@param.output()
def output(self):
    return any_object_you_want
```
?

**Comment by kcpevey** [comment]
Supposing I don't care about validating since there is no way to validate a custom class object.

**Comment by philippjfr** [comment]
Yes you can, if you want to name the output something other than the method name you will have to use this signature though:

```
@param.output(other_name=param.Parameter)
def output(self):
    return any_object_you_want
```

**Comment by kcpevey** [comment]
Can there be more than one output?   
   
`@param.output(other_name=param.Parameter, second_thing=param.Parameter)`   
   
Seems like it doesn't like that, but I might have something else wrong:  
  
```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-8-45e9e38c288f> in <module>
      2 load_sim_widget = model.load_adh_simulation
      3 
----> 4 class InputData(load_sim_widget):
      5 #     adh_root_filename = param.String(default='NoKo_1', precedence=1)
      6 #     adh_directory = param.String(default='/Users/rdchlkcp/ers/testing/dambreak', precedence=2)

<ipython-input-8-45e9e38c288f> in InputData()
     20     print(load_sim_widget.adh_root_filename)
     21 
---> 22     @param.output(adh_viz=model.adhViz, adh_model=adhModel)
     23     def output(self):
     24 #         adh_viz = self.run()

~/ers/gitHub/param/master/param/param/parameterized.py in <lambda>(actual_f)
    206     @wraps(f)
    207     def _f(*args, **kwargs):
--> 208         return lambda actual_f: f(actual_f, *args, **kwargs)
    209     return _f
    210 

~/ers/gitHub/param/master/param/param/parameterized.py in output(func, *output, **kw)
    274         name, otype = None, output[0]
    275     elif kw:
--> 276         assert len(kw) <= 1
    277         name, otype = list(kw.items())[0]
    278     else:

AssertionError: 
```  
  
And the above is correct, the assertion error is empty.

**Comment by philippjfr** [comment]
No, a single output per method, but the output can be a dictionary/list containing multiple objects if you want.

**Comment by kcpevey** [comment]
Hmm. Tried that, it didn't work. I'll look into it more.

**Comment by philippjfr** [comment]
Closing since it's mostly a usage issue. Please reopen if there is an actual bug here.
