### ISSUE TITLE
Duplicate matplotlib output

### ISSUE THREAD

**Issue by jbednar** [pyviz/panel#162]
If I make a simple mpl-based plot and use it with interact in the same Jupyter notebook cell:

```
import panel as pn, numpy as np, pandas as pd, matplotlib.pyplot as plt
pn.extension()

def sine(frequency=1.0, amplitude=1.0, n=200):
    xs = np.arange(n)/n*20.0
    ys = amplitude*np.sin(frequency*xs)
    df = pd.DataFrame(dict(y=ys), index=xs)
    return df.plot().get_figure()

pn.interact(sine)
```

I get widgets and a plot that updates as expected:

![image](https://user-images.githubusercontent.com/1695496/48721827-46595600-ebe8-11e8-8188-1f2b22d134f5.png)

But then in the very next cell I use the same code and get two plots, one that updates and one that doesn't:

![image](https://user-images.githubusercontent.com/1695496/48721865-5bce8000-ebe8-11e8-96de-e69b366703f6.png)

Anyone have an idea why this happens?

**Comment by jbednar** [comment]
It looks like I get two copies of the output in any cell *after* the cell that includes `import matplotlib.pyplot as plt`.  Maybe that import is registering something with Jupyter that is meant to display the figure, but here is just causing me headaches?

**Comment by xavArtley** [comment]
import panel as pn, numpy as np, pandas as pd
import matplotlib as mpl
mpl.use('Agg')
import matplotlib.pyplot as plt
pn.extension()


def sine(frequency=1.0, amplitude=1.0, n=200):
    xs = np.arange(n)/n*20.0
    ys = amplitude*np.sin(frequency*xs)
    df = pd.DataFrame(dict(y=ys), index=xs)
    return df.plot().get_figure()

pn.interact(sine)

**Comment by jbednar** [comment]
Thanks, that helps.  It's very annoying to have to do that!

**Comment by jbednar** [comment]
Thanks!  That approach is much more reasonable, though still a bit clunky:

```
import panel as pn, numpy as np, pandas as pd, matplotlib.pyplot as plt
%matplotlib inline

def mplplot(df):
    fig = df.plot().get_figure()
    plt.close(fig)
    return fig

def sine(frequency=1.0, amplitude=1.0, n=200, fn=mplplot):
    xs = np.arange(n)/n*20.0
    ys = amplitude*np.sin(frequency*xs)
    df = pd.DataFrame(dict(y=ys), index=xs)
    return fn(df)

sine(1.5, 2.5)
```


```
import panel as pn
pn.extension()

pn.interact(sine)
```
