### ISSUE TITLE
Change the width of Pipeline next/previous buttons

### ISSUE THREAD

**Issue by kcpevey** [pyviz/panel#164]
Is the ability to change the width of the pipeline buttons exposed? How would one go about doing that?

**Comment by xavArtley** [comment]
I don't think it's exposed but you can do this :
```
pipeline.layout[0][1]._widget_box.width = 100
pipeline.layout[0][2]._widget_box.width = 100
pipeline.layout
```

**Comment by kcpevey** [comment]
That works, thanks!
