### ISSUE TITLE
Arguments with no widgets shouldn't be an error

### ISSUE THREAD

**Issue by jbednar** [pyviz/panel#165]
If I create a function with an argument that's a callable, the function works fine by itself:

```
import panel as pn, numpy as np, pandas as pd, matplotlib.pyplot as plt
%matplotlib inline

def mplplot(df):
    fig = df.plot().get_figure()
    plt.close(fig)
    return fig

def sine(frequency=1.0, amplitude=1.0, n=200, fn=mplplot):
    xs = np.arange(n)/n*20.0
    ys = amplitude*np.sin(frequency*xs)
    df = pd.DataFrame(dict(y=ys), index=xs)
    return fn(df)

sine(1.5, 2.5)
```
![screen shot 2018-11-20 at 2 06 05 pm](https://user-images.githubusercontent.com/1695496/48799691-729ad280-eccd-11e8-8c1d-a36a26035280.png)

But `pn.interact` balks:

```
import panel as pn
pn.extension()

pn.interact(sine)
```

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-14-78433f5ebfe2> in <module>()
      2 pn.extension()
      3 
----> 4 pn.interact(sine)

~/panel/panel/interact.py in __call__(self, _InteractFactory__interact_f, **kwargs)
    435         #    def f(*args, **kwargs):
    436         #        ...
--> 437         w = self.widget(f)
    438         try:
    439             f.widget = w

~/panel/panel/interact.py in widget(self, f)
    360             The function to which the interactive widgets are tied.
    361         """
--> 362         return self.cls(f, self.opts, **self.kwargs)
    363 
    364     def __call__(self, __interact_f=None, **kwargs):

~/panel/panel/interact.py in __init__(self, object, params, **kwargs)
    132             getcallargs(object, **{n:v for n,v,_ in new_kwargs})
    133 
--> 134         widgets = self.widgets_from_abbreviations(new_kwargs)
    135         if self.manual_update:
    136             widgets.append(('manual', Button(name=self.manual_name)))

~/panel/panel/interact.py in widgets_from_abbreviations(self, seq)
    221             if not (isinstance(widget, Widget) or isinstance(widget, fixed)):
    222                 if widget is None:
--> 223                     raise ValueError("{!r} cannot be transformed to a widget".format(abbrev))
    224                 else:
    225                     raise TypeError("{!r} is not a ValueWidget".format(widget))

ValueError: <function mplplot at 0x118981a60> cannot be transformed to a widget
```

In this case, shouldn't `pn.interact` simply assume that any argument it doesn't know how to make a widget for should be left at its default value?  I don't see why we should be making users declare something special about that argument (which is of course possible), when the point of `interact` is to quickly pop up some widgets to control whatever can be done automatically.

**Comment by jbednar** [comment]
One could argue for popping up a read-only widget for that argument, but I'd think the most useful default is for those arguments to simply not appear.

**Comment by jbednar** [comment]
The same thing happens for arguments whose default value is `None`, and again I'd want that argument simply to be ignored as obviously not something interact can synthesize into a widget without more information.

**Comment by philippjfr** [comment]
So we are simply following the ipywidgets interact behavior here. I'd be okay changing the behavior but we should be very clear in deciding to what extent we match the ipywidgets API.

**Comment by jbednar** [comment]
I'd rather do the more useful thing for the user.  It does mean that Panel will work with functions that ipywidgets will balk at, but I don't think that's a problem.

**Comment by philippjfr** [comment]
Note that ipywidgets does do something semi-useful for some default args, e.g. numbers even without bounds get converted to sliders.
