### ISSUE TITLE
Displaying certain Parameter attributes of Parameterized

### ISSUE THREAD

**Issue by MHC03** [pyviz/panel#166]
Is it possible to pick and arrange all Parameters of a Parameterized object? Let's say we have following class:
```python
class Options(param.Parameterized):
    left_slider = param.Number(default=0, bounds=(0, 10))
    left_button = param.Action(doc='Something')
    right_slider = param.Number(default=0, bounds=(0, 10))
    right_button = param.Action(doc='Something')
```

Now I would like to arange my widgets manually, suppose like this:
```python
ops = Options()
left_side = pn.layout.WidgetBox(ops.params('left_slider'), ops.params('left_button'))
right_side = pn.layout.WidgetBox(ops.params('right_slider'), ops.params('right_button'))
pn.Row(left_side, right_side)
```

Obviously the code doesn't work as intended, but is there a way to do this?

**Comment by jbednar** [comment]
Sure:

```
ops = pn.panel(Options())[0]
left_side  = pn.layout.WidgetBox(ops[1], ops[2])
right_side = pn.layout.WidgetBox(ops[3], ops[4])
pn.Row(left_side, right_side)
```
![image](https://user-images.githubusercontent.com/1695496/48860213-e0a2d080-ed85-11e8-870f-fc89195b8de1.png)

You can figure out the indexing involved by printing the representation of a Panel object, which shows you that the index of `left_button` is `[0][1]`:

```
print(pn.panel(Options()))

Column(name='Options00104')
    [0] WidgetBox(name='Options00104', width=300)
        [0] StaticText(value='<b>Options</b>')
        [1] Button(button_type='success', name='Left button')
        [2] FloatSlider(end=10, name='Left slider', start=0, value=0)
        [3] Button(button_type='success', name='Right button')
        [4] FloatSlider(end=10, name='Right slider', start=0, value=0)
```

**Comment by philippjfr** [comment]
Alternatively this also works:

```
class Options(param.Parameterized):
    left_slider = param.Number(default=0, bounds=(0, 10))
    left_button = param.Action(doc='Something')
    right_slider = param.Number(default=0, bounds=(0, 10))
    right_button = param.Action(doc='Something')
    
left = pn.panel(Options, parameters=['left_button', 'left_slider'])
right = pn.panel(Options, parameters=['right_button', 'right_slider'])
pn.Row(left, right)
```

**Comment by jbednar** [comment]
Or the same but with the instance as in the original example:

```
ops = Options()

left = pn.panel( ops, parameters=['left_button',  'left_slider'])
right = pn.panel(ops, parameters=['right_button', 'right_slider'])
pn.Row(left, right)
```

**Comment by MHC03** [comment]
> 
> 
> Or the same but with the instance as in the original example:
> 
> ```
> ops = Options()
> 
> left = pn.panel( ops, parameters=['left_button',  'left_slider'])
> right = pn.panel(ops, parameters=['right_button', 'right_slider'])
> pn.Row(left, right)
> ```

Thank you both very much. Just one quick question:

Can I disable panel to order the parameters alphabetically? (If needed, I can open a new issue)

**Comment by jbednar** [comment]
I'd be happy to have an option to do that.  The sorting is controlled by key_fn in [_get_widgets](https://github.com/pyviz/panel/blob/master/panel/param.py#L342), and one could add a parameter allowing users to supply another sorting function instead.  PRs welcome!

**Comment by MHC03** [comment]
Currently I am fairly busy, but I could try to add that functionality later.
