### ISSUE TITLE
How to make Panel widget scrubber wider?

### ISSUE THREAD

**Issue by neocronomican** [pyviz/panel#170]
Hi 

I have problem when I use  `all_map = pn.panel(hv_obj1 + hv_obj2, widget_type=scrubber) `  but the scrubber button does not show in wide layout (see image below)

how to set the scrubber button to make it wider?

thank you very much

![selection_033](https://user-images.githubusercontent.com/37390012/49229213-64b52200-f430-11e8-8674-26af8dd54bcc.png)

**Comment by philippjfr** [comment]
Like all other objects in panel you can view the subobjects using pprint, index into layouts and modify parameters. In this case you can set the width with:

```python
all_map = pn.panel(hv_obj1 + hv_obj2, widget_type=scrubber)
all_map[1].width = 500
```
