### ISSUE TITLE
Add a border to panel.show()

### ISSUE THREAD

**Issue by kcpevey** [pyviz/panel#173]
Is there a way to add a simple line border to the displayed panel?

**Comment by philippjfr** [comment]
You can now define custom CSS via the extension or using ``pn.config`` and then use the defined css classes:

```python
import numpy as np
import panel as pn

raw_css = """
div.panel-column {
    border: 1px black solid
}
"""

# Either in the extension
pn.extension(raw_css=[raw_css])

# Or by setting the config directly
pn.config.raw_css.append(raw_css)
```

Once the CSS is defined you can define a CSS class on a Column to achieve a border:

```python
pn.Column('# Some text', css_classes=['panel-column'])
```

![Screen Shot 2019-03-24 at 5 37 00 PM](https://user-images.githubusercontent.com/1550771/54883220-76955780-4e5b-11e9-8e58-0ed72e14a4f2.png)
