### ISSUE TITLE
Javascript uncaught type error when dmap displayed with panel

### ISSUE THREAD

**Issue by xavArtley** [pyviz/panel#174]
when I execute this code :
```
import panel as pn
import holoviews as hv
import pandas as pd
import numpy as np
pn.extension()
df = pd.DataFrame(np.random.rand(10,3), columns=['x','y','z'])
dmap = hv.Dataset(df).to(hv.Points, ['x', 'y'], dynamic=True)
pn.panel(dmap)
```
Everything seems ok except when I use the slider I have a javascript trace:
![image](https://user-images.githubusercontent.com/18531147/49316474-5a0e9180-f4f1-11e8-8620-72a4523d91d1.png)
the first trace is when I grab the slider and the second one on mouse release

**Comment by philippjfr** [comment]
Thanks, @xavArtley. I've looked into this briefly before, but couldn't quite figure out where the error orginates from.

**Comment by philippjfr** [comment]
This was fixed in https://github.com/bokeh/bokeh/pull/9042
