### ISSUE TITLE
KeyError when adding a new value to a Select widget

### ISSUE THREAD

**Issue by sdc50** [pyviz/panel#182]
Panel does not support updating/adding to the options of a `ObjectSelector` once the `Select` widget has been created.

See the following code to reproduce the error:
![image](https://user-images.githubusercontent.com/6454472/50020167-bdd99580-ff9a-11e8-9a77-e8d024f4ad52.png)

**Comment by philippjfr** [comment]
I don't think `Panel` should handle `check_on_set` to be honest, if you want to add new options I think you should actually add them to the `objects` on the parameter. `check_on_set` makes sense for param but it shouldn't force panel to modify the param object or expand the list of options.
