### ISSUE TITLE
Respect name of interact() object

### ISSUE THREAD

**Issue by jbednar** [pyviz/panel#183]
Right now, `pn.interact()` accepts a `name=` argument and appears to provide it to the result of the function call, but that value isn't shown anywhere:

![image](https://user-images.githubusercontent.com/1695496/50188357-040a5e00-02e7-11e9-88c5-4f17202fe262.png)

Could we have name be a title that's given to the whole app instead, which seems much more useful?  I.e., can it act like:

![image](https://user-images.githubusercontent.com/1695496/50188449-52b7f800-02e7-11e9-9d67-a28f51534ff8.png)

**Comment by philippjfr** [comment]
The problem with adding any keywords to interact is that it reserves that keyword. However it's also worth noting that because any parameters defined on ``interactive`` are already treated this way and that includes ``name`` already.
