### ISSUE TITLE
Rows with objects of non-default width

### ISSUE THREAD

**Issue by wabu** [pyviz/panel#197]
If you create a row with elements of non-default width, the standard width will be used. Once the row is show, when you reassign the objects, the width of the objects will be respected. It'd expect the width to be respected even without reassigning the objects.

```python
import panel as pn

row = pn.Row(pn.widgets.Button(name="A", width=40), pn.widgets.Button(name="Actoin"), pn.widgets.Button(name="B", width=40))
row
```
![spacing](https://user-images.githubusercontent.com/39164/50682649-d83de680-100f-11e9-9f42-16b27912bafe.png)

```python
row.objects = row.objects
```
![alligned](https://user-images.githubusercontent.com/39164/50682682-eb50b680-100f-11e9-8fb1-a5b82286ead6.png)

- panel 0.3.1
- bokeh 1.0.0

**Comment by xavArtley** [comment]
Widgets should always be embed in a widgetbox:
I don't thik it's documented on panel but it is on bokeh
https://bokeh.pydata.org/en/latest/docs/user_guide/layout.html
```
import panel as pn
from panel.layout import WidgetBox as wb

row = pn.Row(wb(pn.widgets.Button(name="A"), width=40), wb(pn.widgets.Button(name="Action")), wb(pn.widgets.Button(name="B"), width=40))
row
```
However the reassigning behavior seems wrong. As there is no change between objects in the Row nothing should happen

**Comment by philippjfr** [comment]
This now works fine on master:

![screen shot 2019-03-01 at 4 24 57 am](https://user-images.githubusercontent.com/1550771/53616355-199ade80-3bda-11e9-9c58-e3c21f313bf4.png)
