### ISSUE TITLE
Supported object types and libraries

### ISSUE THREAD

**Issue by jbednar** [pyviz/panel#2]
This library is designed to be very inclusive about providing basic support for a large number of different types of viewable objects.  In categories ordered by decreasing richness of the representation, the supported types are:

* Interactive plots -- implemented specifically for each library:
  - [x] Bokeh plots
  - [x] Plotly plots
  - [x] Altair or Vega plots
  - [x] HoloViews plots
     - [x] hvPlot plots for Pandas, XArray, Dask, Streamz, Intake, and GeoPandas data (via Bokeh+HoloViews)
* Image-based plots -- implemented specifically for each library, but trivial to add more:
  - [x] Matplotlib figures (as PNG)
      - [x] Seaborn plots (generates Matplotlib figures)
      - [x] plotnine plots (generates Matplotlib figures; superseding Python ggpy/ggplot2)
  - [x] R ggplot2 plots (via rpy2, as PNG)
  - [x] yt plots (as Matplotlib PNG)
* Images -- PNG, JPG, or GIF:
  - [x] anything with a `_repr_png_` method allowing rich display in IPython, including:
      - [x] IPython.display.Image
      - [x] PIL/Pillow images
      - [x] Datashader images
      - [x] NetworkX graph, plotted using dot/graphviz using nxpd
  - [x] anything with a `_repr_jpg_` method allowing rich display in IPython
  - [x] anything with a `_repr_svg_` method allowing rich display in IPython 
       - [x] Shapely images
       - [x] Dot/Graphviz Graph/DiGraph objects
  - [x] files on the local filesystem ending in `.png`, `.jpg`, `.svg`, or `.gif`
  - [x] image URLs ending in `.png`, `.jpg`, `.svg`,  or `.gif`.
* Markdown -- anything with a `_repr_markdown_` method allowing rich display in IPython, including:
  - [x] Markdown text as Python strings 
* HTML -- anything with a `_repr_html_` method allowing rich display in IPython, including:
  - [x] HTML code as Python strings
  - [x] Pandas dataframes (as a table; requires height specification)
* Equations -- anything with `_repr_latex_`
  - [x] Equations as LaTeX strings (via matplotlib and Pillow)
  - [x] IPython.display.Latex objects
* Widgets -- based on Bokeh widgets:
  - [x] Bokeh widgets (wrapped as panel.widgets)
  - [x] Parameterized objects (parameters from Param automatically mapped to panel.widgets)
* Str -- preformatted text representing anything displayed using Python's `str()` function:
  - [x] any Python object

The library selects the richest representation available (higher in this list) unless explicitly requested.  We can consider adding specific support for other types of representations:

  - [ ] streamz objects?
  - [ ] sympy objects?
  
Other objects that are tightly bound to ipywidgets seem like they would take superhuman effort to support, at least if we wanted them to work outside the notebook context:
  
  - [ ] bqplot
  - [ ] ipyvolume
  - [ ] plotly 3.0-specific features
  
But maybe someone could suggest a way to use these without replicating the full ipywidgets API?  Other suggestions for representation types can be added by editing this comment or adding new comments below.

**Comment by jlstevens** [comment]
You could choose to display any Python object that supports ``__str__`` or ``__repr__`` so that Panel can genuinely display everything (even if the textual representation isn't actually appropriate!).

**Comment by jbednar** [comment]
All types we listed as hoping to support are now included, so this issue can be closed.  Additional types can of course be added as needed over time.

**Comment by jbednar** [comment]
And, as of Panel 0.10.0, even the ipywidgets-based functionality we hadn't expected to be able to support should work now!
