### ISSUE TITLE
entering two different invalid values into LiteralInput consecutively causes '(invalid)' message to disappear

### ISSUE THREAD

**Issue by lebedov** [pyviz/panel#202]
When using Panel 0.3.1, if I create a `panel.widgets.LiteralInput`, enter an invalid value (e.g., `a`) and press Enter, and then enter a different invalid value (e.g., `b`) and press Enter, the `(invalid)` message above the widget appears after the first entry and then disappears after the second. Shouldn't the message remain present after the second entry?

**Comment by philippjfr** [comment]
I think this was addressed by the linked PR.
