### ISSUE TITLE
panel CLI commands not working on Windows

### ISSUE THREAD

**Issue by philippjfr** [pyviz/panel#206]
According to several windows users ``panel`` CLI commands are not working on Windows raising errors like "panel command is not recognized". According to those same users bokeh commands do work so there is something about the panel setup of the entry points that's not quite right.

Bokeh also has a ``__main__.py`` (see https://github.com/bokeh/bokeh/blob/master/bokeh/__main__.py), which is not present in panel, could this be related?

**Comment by philippjfr** [comment]
It's not bokeh's approach, python on Windows should always generate exe files for any console scripts.

**Comment by DancingQuanta** [comment]
Um, running `panel serve` in windows cmd (in anaconda prompt) on my personal laptop launched a bokeh server without any issues. And the `panel` cli file do not have any extension. I think I configured my laptop to be able to do this but not my work laptop.

Will have to test `anaconda prompt` on my work laptop (windows 7).

Regarding the console scripts entry points, `.exe` is not generated for `panel` or `holoviews`. Please see below for my personal `anaconda prompt`.
```
(raman) C:\Users\andre>where bokeh
C:\Users\andre\Miniconda3\envs\raman\Scripts\bokeh.exe
^C
(raman) C:\Users\andre>where panel
C:\Users\andre\Miniconda3\envs\raman\Scripts\panel

(raman) C:\Users\andre>where holoviews
C:\Users\andre\Miniconda3\envs\raman\Scripts\holoviews
```
`bokeh.exe` is not editable to me apart from `panel' or `holoviews`.

It would be good if other windows users document any issues they already have here.

**Comment by philippjfr** [comment]
Right the question is why it isn't doing the same thing for panel already. Afaik nothing special **should** be needed for that to happen.

**Comment by ceball** [comment]
Is this for installation via conda or pip?

If via conda, are holoviews and panel missing entrypoints in their conda
recipes? (I am only replying by email on phone here without being able to
check.)

For panel, you can see an example of what you could copy in e.g.
datashader, where the conda entrypoints are templated from setup.py. When I
set up panel i think there were no entry points, though I probably should
have added the entrypoint templating in the conda recipe anyway.

As an aside, in the next version of pyctdev, writing a conda recipe in each
project will not be necessary, as it can generate conda recipes on the fly
while packaging. (If necessary, the generated recipe can subsequently be
modified by hand and kept around if e.g. pyctdev does not support something
that can be expressed in a conda recipe etc.)

**Comment by philippjfr** [comment]
Thanks @ceball, that's probably it. I'll  make a PR with the templating and then cut a dev release.

**Comment by xavArtley** [comment]
Why not adding a `__main__.py`?
There are some windows bugs where the `python -m` is convenient as workaround
For example https://github.com/bokeh/bokeh/issues/8529

**Comment by ceball** [comment]
Yes, I agree, projects should use __main__.py (e.g. to support python -m);
I brought that up in the past (I think!). I'm not sure what the reason was
for choosing not to do it.

Earlier, I was only suggesting the reason for the missing exe. I.e. adding
__main__.py is a good idea, but wouldn't make an exe file appear (although
you could then of course work around the exe being missing, by using python
-m).

**Comment by philippjfr** [comment]
I just got set up my windows 7 machine and managed to run both ``panel serve`` and ``python -m panel serve`` without issue so I'm going to consider this resolved. Please reopen if you encounter further issues.

**Comment by philippjfr** [comment]
Thanks again @ceball.

**Comment by DancingQuanta** [comment]
Installed `panel 1.3.0` via `pip` on windows and `panel` cli is `panel.exe` which can be executed easily.

To sum it up, conda recipe entry point was the issue here and is resolved as far as I am concerned.

**Comment by whimian** [comment]
@DancingQuanta 

I installed `panel` on windows 10 with `conda install -c pyviz panel`, the installed version is 0.6.2. There is still no `panel.exe` in `/Scripts` directory.
