### ISSUE TITLE
Interaction between Panel, bokeh and Jupyter Notebook format prevents bokeh serve from running with charmap error

### ISSUE THREAD

**Issue by flothesof** [pyviz/panel#208]
Hi,
I'm trying to run the following script using Holoviews (with Bokeh) and Panel in a .ipynb.

```python
import numpy as np
import panel as pn
import param
import holoviews as hv
hv.extension('bokeh')

def gaussian_func(x, x0, amplitude, sigma):
    return amplitude * np.exp(-(x - x0)**2/sigma)

class App(param.Parameterized):
    sigma = param.Number(default=0.1, bounds=(0, 20))
    
    def view(self):
        x = np.linspace(0, 10)
        vals = gaussian_func(x, 5, 1., self.sigma)
        return hv.Curve((x, vals))

app = App(name="Test app")
panel = pn.Row(app, app.view)
panel.servable()
```
If I copy this in a Jupyter Notebook cell, execute the content of the cell, save the result to a notebook called 'bokeh_serve_bug' and then try to serve this file with:
`bokeh serve --show "bokeh_serve_bug.ipynb"`
I get an error:
`ERROR: 'charmap' codec can't decode byte 0x9d in position 1052656: character maps to <undefined>`
Thanks to @xavArtley, we've been able to track down the bug to this by jumping to position 1052656:
`"              first.appendChild(document.createTextNode('❚◀◀'));\n",`

As far as I understand the problem, the analysis is then:
- the Jupyter notebook serializes the panel
- therefore including the JS sources for the Player element (unused here, but still included)
- the player uses a unicode character which maps to undefined
- causing bokeh serve to not work

From my point of view as an user, this is a problem since I expect the bokeh server to run based on the source code, and should ignore any output!

What should be done with this? How could it be fixed?

Thanks for your help

Florian

**Comment by philippjfr** [comment]
Could you provide a bit more detail such as the versions of the various libraries involved as well as your Python version? I can't reproduce any problems running the example. I also don't quite understand how the problem occurs, because bokeh does indeed convert the ipynb source to a Python script and drops any output in the notebook in the process. The complete traceback may therefore also be helpful.

**Comment by flothesof** [comment]
Sure, here are the versions I'm using:
- python 3.6.4
- jupyter notebook 5.4.1
- bokeh 1.0.0
- panel 0.3.1
- holoviews 1.11.0

The traceback I gave above is the complete traceback I get.

**Comment by philippjfr** [comment]
Okay, bizarre, I have all the same versions and can't reproduce the issue at all.

**Comment by xavArtley** [comment]
I think it's specific issue to windows

**Comment by xavArtley** [comment]
The error occur in nbformat line 141:
`return reads(fp.read(), as_version, **kwargs)`

**Comment by xavArtley** [comment]
If I replace special character by their unicode representation I have no issue anymore.
![image](https://user-images.githubusercontent.com/18531147/50984583-88c15400-1502-11e9-9cae-e6381b0346c3.png)
