### ISSUE TITLE
General Question: Audio player widget

### ISSUE THREAD

**Issue by ThetomekK** [pyviz/panel#210]
Hi there, 

Do you think, it is possible to implement a kind of audio player widget for panel? 

I'm looking for a possibility to show the audio raw data and/or the spectrogram (2D numpy array) and play the underlying audio. 

Thanks for your opinions.

**Comment by philippjfr** [comment]
I don't see why not, I'd happily accept a PR adding one. Should be easy to add a model which renders an ``audio`` HTML tag and populates it with base64 encoded data or a URL pointing to a remote audio file. If you feel up to working on this I'm happy to provide pointers, something like [FileInput](https://github.com/pyviz/panel/blob/master/panel/models/fileinput.ts) model would be a reasonable starting point.

**Comment by philippjfr** [comment]
If we're adding an AudioWidget we might as well add a VideoWidget too.

**Comment by jbednar** [comment]
I already demonstrated video working via YouTube, which was trivial, but I can't remember what I did with that example...

**Comment by philippjfr** [comment]
That's not really what I was talking about, I was imagining a dedicated widget which you could point to a local or remote mp4/webm/... file. You could probably already to this using a Div but a dedicated widget seems sensible so you can more easily embed it and so a user does not need to know too much about HTML.

**Comment by philippjfr** [comment]
Sure, a simple wrapper around YouTube videos makes sense too and wouldn't need a custom bokeh model either.

**Comment by ea42gh** [comment]
Documentation: show an "intro to holoviews talk", e.g., from one of the conferences you presented at :-)

**Comment by philippjfr** [comment]
@ThetomekK Could you try out #215 where I've implemented the Audio model?
