### ISSUE TITLE
Labeling Tabs Documentation

### ISSUE THREAD

**Issue by ahuang11** [pyviz/panel#211]
I had a hard  time figuring out how to label the tabs in pn.Tabs:

Initially, I thought it was 
```
curve1 = hv.Curve(([0, 1], [0, 1]))
curve2 = hv.Curve(([0, 1], [0, 3]))
pn.Tabs({'curv1': curve1, 'curv2': curve2})
```

Then I tried:
```
curve1 = hv.Curve(([0, 1], [0, 1]))
curve2 = hv.Curve(([0, 1], [0, 3]))
pn.Tabs({'curv1': pn.Pane(curve1), 'curv2': pn.Pane(curve2)})
```

Finally I figured out this was the solution.
```
curve1 = hv.Curve(([0, 1], [0, 1]))
curve2 = hv.Curve(([0, 1], [0, 3]))
pn.Tabs(pn.Pane(curve1, name='curv1'), pn.Pane(curve2, name='curv2'))
```

**Comment by philippjfr** [comment]
It definitely still needs to be documented but I started reworking how the labelling works in https://github.com/pyviz/panel/pull/152 because it's confusing right now.

**Comment by jsignell** [comment]
Note that after #152 tab titles can also be set using tuples like:

```python
curve1 = hv.Curve(([0, 1], [0, 1]))
curve2 = hv.Curve(([0, 1], [0, 3]))
pn.Tabs(('curve1', curve1), ('curve2', curve2))
```

**Comment by philippjfr** [comment]
This should now be sufficiently documented in the [Tabs reference entry](http://panel.pyviz.org/reference/layouts/Tabs.html). Please reopen and/or submit a PR if you think it requires further clarification.
