### ISSUE TITLE
Control pipeline transitions from within stages

### ISSUE THREAD

**Issue by DancingQuanta** [pyviz/panel#219]
I want to be able to decide whether a user can proceed to next stage in a Pipeline. This will involve disabling the `Next` button and the button would be enabled if a condition is met.

In my only Pipeline app, my first stage was loading a data file. I wish to be able to prevent the user from advancing to the next stage before properly loading the data.

**Comment by kcpevey** [comment]
+1  This would be very useful to me too!

**Comment by philippjfr** [comment]
Sure I could simply make the ``previous`` and ``next`` methods on the Pipeline public.
