### ISSUE TITLE
ColumnDataSource's columns must be of the same length. 

### ISSUE THREAD

**Issue by orkun** [pyviz/panel#226]
Hi, 
I try to use panel 3d plotly surface when I give x,y axes parameter in 3d surface as ```surface =go.Surface(x=xutm , y=yutm ,z=z,colorscale='Earth')``` ```pn.panel(plotly_layout).servable()``` gives this error : 
ColumnDataSource's columns must be of the same length. Current lengths: ('x', 78), ('y', 49), ('z', 65) when I omit x,y axes, it works.
Regards

**Comment by kcpevey** [comment]
I think your lengths for x, y, and z will all need to be equal.

**Comment by philippjfr** [comment]
That's a faulty assumption I made when I implemented the plotly model, that requirement makes sense for columnar data but for 2D or 3D data it doesn't apply. Will have to refine the Plotly model a bit.

**Comment by philippjfr** [comment]
Now fixed on master.
