### ISSUE TITLE
view vs. viewable in examples?

### ISSUE THREAD

**Issue by jbednar** [pyviz/panel#227]
Our Panel examples use one of two different ways to update a plot of a Parameterized object:

1. Providing a method on the Parameterized object that Panel can call whenever a plot needs to be updated, as in [yesterday's version of the pyviz 01 tutorial](http://pyviz.org/tutorial/01_Workflow_Introduction.html):

```
class E(param.Parameterized):
    alpha = param.Magnitude(default=0.75, doc="Map tile opacity")
    cmap = param.ObjectSelector('fire', objects=['fire','bgy','bgyw','bmy','gray','kbc'])
    location = param.ObjectSelector(default='dropoff', objects=['dropoff', 'pickup'])

    def make_view(self, **kwargs):
        pts   = hv.Points(taxi, [self.location+'_x', self.location+'_y'])
        trips = datashade(pts, cmap=palette[self.cmap], **dopts)
        return tiles.options(alpha=self.alpha) * trips

e = E(name="Taxi explorer")
pn.Row(e.param, e.make_view)
```

2. Providing a method whose *return value* is passed to Panel, as in the "viewable" method on [dashboard.ipynb](https://github.com/pyviz/datashader/blob/master/examples/dashboard.ipynb):
```
class E(param.Parameterized):
...
    def viewable(self,**kwargs):
        ...
        return hv.DynamicMap(...)

e = E()
pn.Row(explorer.param, explorer.viewable())
```

Basically, either Panel gets a new plot by calling a method (with Panel knowing which parameters to watch), or it displays what it considers a static plot that itself is watching parameters and reacts internally when they are changed. This distinction is very subtle (only different by "()"), but crucial, and so I'd like to make it more obvious which approach any given example is using.  Can we give them names that help people realize which is which?

One possibility: "e.view" for case 1 and "e.viewable()" for case 2?  I.e. a verb (though also unfortunately a noun) when it's a method to call, and an adjective (though also unfortunately a noun) when the method name is describing what it will return. It's subtle, though, and it would be nicer to have something more obvious.  Possible things to focus on: one's reactive, the other is imperative, one is displaying current state, the other is an object that watches state itself, ...

**Comment by jbednar** [comment]
Unfortunately "display" is *also* both a noun and a verb in English, and thus seems ambiguous as well.

**Comment by philippjfr** [comment]
Yeah -1 on ``display``, I think ``view`` and ``viewable`` is reasonably clear.

>I think maybe viewable conveys a stateful object that changes (with an updating view on it) while maybe display conveys a transitory snapshot of the current state?

Both would fall under ``viewable`` under the definition stated above, a``view`` on the other hand is a method with dependencies which may be reevaluated to generate a new viewable.

**Comment by jbednar** [comment]
Ok, I'll assume `view` for the imperative and `viewable` for generating an object, unless someone comes up with something better.

**Comment by jlstevens** [comment]
>  I think view and viewable is reasonably clear.

I don't *at all* but I also don't have a better suggestion!
