### ISSUE TITLE
Default cell size when using Tabs inside of Columns

### ISSUE THREAD

**Issue by kcpevey** [pyviz/panel#236]
```
import param
import panel as pn

class one(param.Parameterized):
    string_value            = param.String(default="str",doc="A string")
    num_int                 = param.Integer(50000,bounds=(-200,100000))
    
class two(param.Parameterized):
    boolean                 = param.Boolean(True, doc="A sample Boolean parameter")
    
class three(param.Parameterized):
    color                   = param.Color(default='#FFFFFF')
  
```
If we view this with a variety of layouts, some are expected:
`pn.Tabs(one, two)`
![image](https://user-images.githubusercontent.com/15659110/52497577-05942c00-2b9c-11e9-9e3f-2261078c58b2.png)
  
more expected behavior:
`pn.Row(pn.Spacer(height=200), pn.Tabs(one,two), three)`
![image](https://user-images.githubusercontent.com/15659110/52497630-1fce0a00-2b9c-11e9-99c8-407e1c0a4958.png)
  
But when I try to put Tabs into a column, things don't behave correctly.  I seem to lose all but the first tab AND despite that I put that spacer at the bottom, it looks to be adding space at the top AND the bottom.
`pn.Column(pn.Tabs(one,two), pn.Spacer(height=300))`  
![image](https://user-images.githubusercontent.com/15659110/52497685-5015a880-2b9c-11e9-896a-4d1f321a38c8.png)
  
Note that if I remove the spacer, I lose the space at the top, but the cell size isn't rendering correctly by default so you can't see any of the widgets at all.
![image](https://user-images.githubusercontent.com/15659110/52497726-73405800-2b9c-11e9-8620-f072561beeb6.png)  
  
Lastly, my ultimate goal is something like this:
`pn.Column(pn.Tabs(one,two), three)`  
But without the explicit spacer I can't all the widgets
![image](https://user-images.githubusercontent.com/15659110/52498478-83f1cd80-2b9e-11e9-875f-3485210cc2bb.png)
  
  
panel = 0.4.0  
  
Seems like the default sizing for pn.Column isn't behaving properly.

**Comment by philippjfr** [comment]
Will be worth checking whether this is fixed once we're using bokeh with the layout refactor, until then I don't think this is worth investigating.

**Comment by kcpevey** [comment]
Yeah I was wondering about that. Sounds good.

**Comment by philippjfr** [comment]
This is indeed working fine now using panel and bokeh dev, even without the Spacer.
