### ISSUE TITLE
Applying param.Action inside of parameterized class

### ISSUE THREAD

**Issue by kcpevey** [pyviz/panel#239]
I have a parameterized class that is set up to be run alone or within a pipeline stage. I can't seem to get the `param.Action` item linked to a method properly. The only example I can find is with a lambda function which isn't what I need.  
  
Code to recreate:
```
class Stage1(param.Parameterized):
    
    a = param.Number(default=5, bounds=(0, 10))

    b = param.Number(default=5, bounds=(0, 10))
    
    button = param.Action(increment)
    
    def increment(self):
        self.a = self.a + 1
    
    @param.output(('c', param.Number), ('d', param.Number))
    def output(self):
        return self.a * self.b, self.a ** self.b
    
    @param.depends('a', 'b')
    def view(self):
        c, d = self.output()
        return pn.pane.LaTeX('${a} * {b} = {c}$\n${a}^{{{b}}} = {d}$'.format(
            a=self.a, b=self.b, c=c, d=d))

    def panel(self):
        return pn.Row(self.param, self.view)
    
stage1 = Stage1()
stage1.panel()
```
  
`button = param.Action(increment)` results in `can't find increment`  
`button = param.Action(self.increment)` results in `can't find self`  
  
I can activate the `increment` method after the class is instantiated so I know that works.

**Comment by philippjfr** [comment]
The only way to make this work is with a function or lambda:

```python
button = param.Action(lambda self: self.increment())
```

**Comment by imroy26** [comment]
How to save this panel as a HTML embed file? will **.save("file_name.html",embed=True)** will work? Thanks!
