### ISSUE TITLE
Panel requires params to be in classes?

### ISSUE THREAD

**Issue by kcpevey** [pyviz/panel#240]
Looking through all the docs, everywhere a param object is displayed, it has to wrapped in an external class first. I just want to display one param object inside of a panel, but I can't figure out the syntax, or is that not possible?  
  
Simple example:
![image](https://user-images.githubusercontent.com/15659110/52738796-10343400-2f95-11e9-8144-0caa6c060cf7.png)
  
  
In my actual code I have a param.Parameterized class (for use with Pipeline) which looks something like this:
```
class GenerateMesh(param.Parameterized):
    redistribute_nodes = param.ClassSelector(class_=RedistributeNodes)
    future_button = param.Boolean(default=True)
  
   def panel()  
          return pn.Row(future_button)
```
but that will just print the VALUE of the param object. I technically do have the option of doing this `pn.panel(mesh_panel.param)` but throws an error because of `param.ClassSelector`:  

```
~/miniconda3/envs/env_name/lib/python3.6/site-packages/panel/layout.py in _get_objects(self, model, old_objects, doc, root, comm)
    244                 child = pane._models[root.ref['id']]
    245             else:
--> 246                 child = pane._get_model(doc, root, model, comm)
    247 
    248             if isinstance(child, BkWidgetBox):

~/miniconda3/envs/env_name/lib/python3.6/site-packages/panel/widgets.py in _get_model(self, doc, root, parent, comm)
     69             parent = _BkWidgetBox()
     70         root = parent if root is None else root
---> 71         model = self._widget_type(**self._init_properties())
     72 
     73         # Link parameters and bokeh model

~/miniconda3/envs/env_name/lib/python3.6/site-packages/panel/widgets.py in _init_properties(self)
     62         properties = {k: v for k, v in self.param.get_param_values()
     63                       if v is not None}
---> 64         return self._process_param_change(properties)
     65 
     66     def _get_model(self, doc, root=None, parent=None, comm=None):

~/miniconda3/envs/env_name/lib/python3.6/site-packages/panel/widgets.py in _process_param_change(self, msg)
    451         mapping = {hashable(v): k for k, v in self.options.items()}
    452         if msg.get('value') is not None:
--> 453             msg['value'] = mapping[hashable(msg['value'])]
    454         if 'options' in msg:
    455             msg['options'] = list(msg['options'])

KeyError: RedistributeNodes(apply=<function RedistributeNodes.<lambda> at 0x1211a61e0>, name='RedistributeNodes06800', node_spacing=1000)  
```  
  
I also have the option of switching to a panel widget `future_button = pn.widgets.Checkbox(name='create mesh', value=True)` which works, but I then when I query was params are in my class, future_button won't show up as a param, which I suspect is why I can't get a `@param.depends` to work correctly with a panel widget.  
   
This seems like a straightforward thing to want to do, and I've tried many things, but nothing seems to fit my use-case. Any ideas?

**Comment by kcpevey** [comment]
Its hard to simplify this issue down, but I think I'm getting there:  
  
After @philippjfr responded to this https://github.com/pyviz/panel/issues/239 I can now see how to use Action button (see the button below). However, based on what @jbednar mentioned on gitter - parameters have to be wrapped in classes before they can be visualized with panel.   
  
So how can I visualize this button given that I'm trying to visualize it INSIDE of this parameterized class?
  
```
class GenerateMesh(param.Parameterized):
    redistribute_nodes = param.ClassSelector(class_=RedistributeNodes)
    future_button = param.Boolean(default=True)
    button = param.Action(lambda self: self.increment())
  
   def increment()
         print('foo')

   def panel()  
          return pn.Row(button)
```

**Comment by philippjfr** [comment]
Maybe I'm missing something but I think what you want is:

```python
class GenerateMesh(param.Parameterized):
    redistribute_nodes = param.ClassSelector(class_=RedistributeNodes)
    future_button = param.Boolean(default=True)
    button = param.Action(lambda self: self.increment())
  
    def increment(self):
        print('foo')

    def panel(self,):
        return pn.panel(self, parameters=['button'])
```

**Comment by kcpevey** [comment]
YES!! I couldn't get the syntax right. I knew there was something like that available, but I couldn't find it in the docs.   
  
Thanks!

**Comment by jbednar** [comment]
Yes, a Parameter only behaves properly in a Parameterized class; the value of that parameter is stored in the Parameterized object's dictionary, with the Parameter object only storing the metadata about the Parameter, not the actual value.  So there is no current way to work fully with a standalone Parameter.  And yes, `@depends` also only works in a Parameterized class's definition; it declares dependencies between parameters and methods of that class. Instead, you should be able to set it up explicitly using widgets and [links](https://panel.pyviz.org/user_guide/Links.html), which is how `@depends` is implemented.

That said, I'm pretty sure it's possible to do what you are trying to do using parameters and their dependencies; I just can't quite figure out what that is.  Can you provide some code that you wish would work, along with a description of what you would have wanted it to do? You do have a code snippet above, but it isn't runnable and I'm not sure what you would expect it to do.  With something a bit more complete it should be simple to translate it to what will actually work.
