### ISSUE TITLE
collections compatibility for Python 3.7+ 

### ISSUE THREAD

**Issue by misolietavec** [pyviz/panel#243]
Starting with Python 3.3 the abstract base types 
`Iterable, Mapping, MutableSequence, MutableMapping`
were moved to submodule `collections.abc`.
But `defaultdict, OrderedDict, namedtuple` must still be imported from `collections`.
In Python 3.7 there are warnings about not using `collections.abc`, in 3.8 that become errors.

**Comment by philippjfr** [comment]
Thanks, should get this into 0.4.1
