### ISSUE TITLE
Change the background color of param text box?

### ISSUE THREAD

**Issue by kcpevey** [pyviz/panel#249]
Is it possible to change the background color of a param.String widget?

**Comment by jsignell** [comment]
There is a background argument available on `pn.pane.Str` 

```python
import panel as pn

pn.pane.Str('132', background='#00ff00')
```

<img width="345" alt="screen shot 2019-03-05 at 9 15 57 am" src="https://user-images.githubusercontent.com/4806877/53811411-50009280-3f27-11e9-9e67-1744fd5e3622.png">

**Comment by kcpevey** [comment]
So this functionality is available via panel widgets, but NOT for param widgets?  
  
```
class foo(param.Parameterized):
    stringthing = param.String('glob', background='#2E4D8A')
pn.Row(foo)
```
Results in the following error:
`TypeError: __init__() got an unexpected keyword argument 'background'`
