### ISSUE TITLE
Broken image link in Django user guide

### ISSUE THREAD

**Issue by jbednar** [pyviz/panel#256]
The link https://panel.pyviz.org/apps/django2/sliders.png in https://panel.pyviz.org/user_guide/Django_Apps.html doesn't seem to go anywhere; was that meant to point to https://parambokeh.pyviz.org/assets/sliders.png ?

**Comment by a-recknagel** [comment]
I'm trying to fix it, but building the docs proves to be a little tricky.

**Comment by a-recknagel** [comment]
Ha, turns out the reason why I couldn't check if my fix was working was because my browser cached the broken link location, how utterly nice of it. Next time I try to fix something in a browser [I should blame caching](https://shouldiblamecaching.com/) from the beginning =/

**Comment by a-recknagel** [comment]
@jbednar I don't see a anything `sliders.png` on that site though, I fixed the only link that I could find on that page, which happened to be broken too. Could you post a screenshot of what you mean?

**Comment by jbednar** [comment]
![image](https://user-images.githubusercontent.com/1695496/66722067-10f4c280-edcf-11e9-8c66-a666953f0a3f.png)
![image](https://user-images.githubusercontent.com/1695496/66722068-16520d00-edcf-11e9-8e6a-db9d046c0585.png)

**Comment by a-recknagel** [comment]
I see, my browser didn't show the broken image thing so I glossed over it. The image exists local to the notebook, but the docs builder doesn't copy that part of the examples tree over, and neither should it. I'll copy it to `_static` and refer that instead.

**Comment by a-recknagel** [comment]
Resolved by #705
