### ISSUE TITLE
Different browsers show panel generated html differently

### ISSUE THREAD

**Issue by Jacob-Barhak** [pyviz/panel#272]
After generating html with panel, different browsers will view the html differently.
This may not be a panel issue, yet since it may cause panels to obscure text, it is worthwhile mentioning.

To see the problem, look at this [interactive poster](https://jacob-barhak.github.io/InteractivePoster_MSM_IMAG_2019.html) made with panel using the [code here](https://github.com/Jacob-Barhak/Presentations/tree/master/PosterIMAG2019). 

If the second tab of this poster is viewed in edge on Windows or chrome on windows or ubuntu  it looks ok. If viewed on Firefox on ubuntu, one will see overlaps of images and text  - see the following image.
![screenshot from 2019-03-05 05-49-45](https://user-images.githubusercontent.com/1986155/53804114-3dc52b00-3f0c-11e9-8020-968c34e1b69e.png) . see how the cluster image cuts the text. The matrix image on the right also cuts the text from the panel above that should have more text.

The image was taken on a a dual screen machine with (1366x768) resolution on Firefox 65.0.164 bit on ubuntu 18.04. Note that this web site shows well on a windows machine running an ubuntu 18.04 VM - so even within the same web browser things are different and this may be a specific hardware or resolution issue. 
 
Using html is not like using a pdf that represents documents better - although also not perfect. However if this is fixable it would be nice.

**Comment by philippjfr** [comment]
Worth revisiting this using panel master, that said any rendering issues like this would have to be reproduced using pure bokeh and filed upstream. So I'll close since there is no action we can take here directly in panel.
