### ISSUE TITLE
Button disabled=True should be more visually distinct

### ISSUE THREAD

**Issue by jsignell** [pyviz/panel#275]
Here I have a some regular button with the last one disabled:

<img width="67" alt="screen shot 2019-03-05 at 9 09 00 am" src="https://user-images.githubusercontent.com/4806877/53811019-58a49900-3f26-11e9-9493-d4fbd7a07949.png">

I propose making the background on the button light gray (same as hover on default button) when disabled==True

**Comment by jbednar** [comment]
Sounds good to me.

**Comment by philippjfr** [comment]
Seems like a bokeh issue, I don't think there's anything we can do about it in panel.

**Comment by philippjfr** [comment]
@jlstevens pointed out that disabled=True is also not very visually distinct for sliders.

**Comment by jsignell** [comment]
Superseded by https://github.com/bokeh/bokeh/issues/8717
