### ISSUE TITLE
Tabs width set on width of contents - truncating tabs

### ISSUE THREAD

**Issue by jsignell** [pyviz/panel#284]
The second tab isn't visible because width is set based on row which seems to have scale_width by default. 

<img width="485" alt="screen shot 2019-03-06 at 8 04 19 am" src="https://user-images.githubusercontent.com/4806877/53883279-89e49e00-3fe6-11e9-8cb3-576f6790fc31.png">

As a work-around I set width on the pn.Rows
<img width="647" alt="screen shot 2019-03-06 at 8 09 16 am" src="https://user-images.githubusercontent.com/4806877/53883510-29099580-3fe7-11e9-81eb-c61d10d34fcd.png">

**Comment by philippjfr** [comment]
This should probably be raised in bokeh.

**Comment by jsignell** [comment]
Raised on bokeh as https://github.com/bokeh/bokeh/issues/8726
