### ISSUE TITLE
Allow empty layouts

### ISSUE THREAD

**Issue by jsignell** [pyviz/panel#285]
I think you mentioned this @philippjfr, but just to capture it. We should hide the bokeh warning since it can be very useful to create an empty layout and then add content to it.

<img width="818" alt="screen shot 2019-03-06 at 12 52 42 pm" src="https://user-images.githubusercontent.com/4806877/53902579-700b8100-400f-11e9-81cd-a4fdda62bca8.png">

**Comment by jsignell** [comment]
I raised the issue of getting rid of the warning on bokeh - if people don't like that idea then we should filter the warning on panel. So I'm leaving this open for now.

**Comment by jlstevens** [comment]
I do think empty layouts ought to be allowed, ideally without any warnings...

**Comment by philippjfr** [comment]
I believe @jsignell will work on making the bokeh warnings configurable in bokeh, which will also let me disable warnings for no renderer warnings in holoviews.

**Comment by jsignell** [comment]
This is in bokeh master and will be in > 1.1.0a9

**Comment by philippjfr** [comment]
Since we handle rendering directly we already silence these warnings now.
