### ISSUE TITLE
Widget state of a panel param not sync with the param value

### ISSUE THREAD

**Issue by xavArtley** [pyviz/panel#287]
MRE :

``` 
class Test(param.Parameterized):
    test = param.Number(default=0)

    @param.depends('test', watch=True)
    def _check_in_bounds(self):
        if self.test > 4:
            self.test = 3

inst = Test()
p = Param(inst.param, parameters=['test'], show_name=False)
pn.panel(p)
```

`inst.test = 1` => sync OK
`inst.test = 5` => sync NOK

**Comment by philippjfr** [comment]
I think events are being swallowed to avoid them bouncing around. I'll look into removing the checks which prevent events from bouncing back and forth and replacing them with some more principled approach.
