### ISSUE TITLE
Change behavior of an application in jupyter or when deployed

### ISSUE THREAD

**Issue by slamer59** [pyviz/panel#294]
In jupyter notebook I design a app like:
```
import numpy as np
import holoviews as hv
hv.extension('bokeh')

frequencies = [0.5, 0.75, 1.0, 1.25]

def sine_curve(phase, freq=0.5):
    xvals = [0.1* i for i in range(100)]
    return hv.Curve((xvals, [np.sin(phase+freq*x) for x in xvals]))

# When run live, this cell's output should match the behavior of the GIF below
dmap = hv.DynamicMap(sine_curve, kdims=['phase'])
pan = pn.Row(dmap.redim.range(phase=(0.5,1)))
pan.servable()
```
which give in the cell:
![image](https://user-images.githubusercontent.com/25283272/54143303-d5091180-4429-11e9-8e9c-ae6acd116516.png)

Now I want to deploy this app with: `panel serve myapp.ipynb`
I want to change let's say the frequency with some request: http://127.0.0.1:5006/myapp?frequency=5
will give me the curve a frequency of 5:

![image](https://user-images.githubusercontent.com/25283272/54143551-595b9480-442a-11e9-877b-d3ea621afd55.png)

How can I do this ?

**Comment by philippjfr** [comment]
Fo reference https://bokeh.pydata.org/en/latest/docs/user_guide/server.html#accessing-the-http-request

**Comment by philippjfr** [comment]
Once merged this will be documented in the Deploy and Export user guide. To summarize, you will be able to access the sessions args on ``pn.state.session_args``.
