### ISSUE TITLE
post bokeh #8740 typescript extensions

### ISSUE THREAD

**Issue by xavArtley** [pyviz/panel#296]
Since bokeh PR : https://github.com/bokeh/bokeh/pull/8740

options has been removed from View.initialize() => current typescript models doesn't compile anymore

**Comment by philippjfr** [comment]
Thanks, I'll make a PR but won't merge until there is a new dev release available.

**Comment by xavArtley** [comment]
I was making a PR too

**Comment by philippjfr** [comment]
Okay let's go with yours then 😄
