### ISSUE TITLE
GoogleMapViewer example menu not updated

### ISSUE THREAD

**Issue by marcbernot** [pyviz/panel#300]
Hello, I try to make the [GoogleMapViewer](https://panel.pyviz.org/user_guide/Param.html) example work. If I replace ```self.param['country'].objects = countries```by ```self.params()['country'].objects = countries```then it works with panel=1.8.2 and panel=0.4, i.e. the country widget entries are updated when you change continent. 
But with either of these syntax the country menu entries are not updated with panel=1.9a3 and param=0.5a3.
By inspecting viewer, it is correct and prints as GoogleMapViewer(continent='Africa', country='Ghana', name='Google Map Viewer') once Africa has been selected.
It thus seems to be a problem with panel not refreshing the country menu view.
This problems occurs in the notebook and in Jupyter lab.

**Comment by philippjfr** [comment]
Thanks for the report, when filing an issue it's always best to check whether it is working on master. Based on my testing it works fine on master and there will be new dev releases and real releases soon.

**Comment by philippjfr** [comment]
The update of the main docs to the new syntax was accidental, and should ideally be reverted.

**Comment by marcbernot** [comment]
Ok thanks, I'll check master next time.
I just checked it and there is an improvement between 0.5a3 and master because the view of the map of the country is updated. But the entries of the menu Country remain the one of Asia even when selecting Africa continent (in notebook and Jupyter lab)

**Comment by philippjfr** [comment]
Thanks, I didn't notice that. That's indeed a bug.

**Comment by philippjfr** [comment]
Fixed in https://github.com/pyviz/param/pull/325

**Comment by philippjfr** [comment]
Fix now merged, and new param dev release is out.
