### ISSUE TITLE
Cross Selector error

### ISSUE THREAD

**Issue by xavArtley** [pyviz/panel#319]
![image](https://user-images.githubusercontent.com/18531147/54675193-5d5c7600-4afe-11e9-8384-9c89215b4db3.png)
![image](https://user-images.githubusercontent.com/18531147/54675243-75cc9080-4afe-11e9-870f-0f4081751f41.png)

**Comment by xavArtley** [comment]
A work around for the moment is to create a dictionnary of the list:
```python
{val:val for in ['a','b','c']}
```

**Comment by philippjfr** [comment]
Yeah, this is a regression from when I made all selectors accept both lists and dicts. Should be an easy fix.
