### ISSUE TITLE
Development version renders markdown differently that previous panel version

### ISSUE THREAD

**Issue by Jacob-Barhak** [pyviz/panel#323]
The development version 0.5.0a3 changed something in markdown. trying  to generate the same code that generated [this poster](https://jacob-barhak.github.io/InteractivePoster_MSM_IMAG_2019.html) , displays different behavior. 

First there are some slight differences in panel sizes - which is expected since some changes were made. However, the Markdown behavior is different.

 When using enumeration or bullets,  all bullets are now indented to the very left of the panel and nested bullets do no work - attached is an image. To the left you see the development panel version 0.5.0a3  and on the right you can see the stable panel 0.4.0. The code to generate this is slightly different, yet the markdown issue is clearly visible. I am using Windows 10 and the image was generated using edge and chrome. 

You can clearly see the bullet and nested bullet issues. And note that bullets are almost invisible since they are pushed so much to the left that its hard to even see its a bullet - the bullet text also is not indented and can be mistaken for continuation of the text - so something seems wrong there. I was handling it so far by using text that look like:
```
&nbsp;&nbsp;&nbsp;- bullet text
```

Yet this is not a good solution for the long run.

![PanelMarkdownDevelopmentVersionIssue](https://user-images.githubusercontent.com/1986155/54792823-c252c180-4c0d-11e9-8f87-6c8e55096e34.png)

Hopefully its sufficient information to locate the cause and fix it.

**Comment by Jacob-Barhak** [comment]
The code that generated the poster can be found [here](https://github.com/Jacob-Barhak/Presentations/tree/master/PosterIMAG2019)

This should help reproduction.

**Comment by philippjfr** [comment]
Thanks @Jacob-Barhak that will be helpful in tracking down what changed.

**Comment by philippjfr** [comment]
Okay, I've tracked down the issue to a change in the bokeh CSS which is central to the layout refactor it seems we should raise this upstream but in the meantime we could simply override the ``ul`` tag CSS.

**Comment by Jacob-Barhak** [comment]
Thanks Philipp,

You may want to also check if this CSS affects markdown table appearance.
The development panel version I used also generates tables that have no
borders.

Not sure what the default behavior should be, yet any type of difference
between cells in markdown tables would be better than the current version
that does not look nice by default as text seems to merge sometimes at cell
boundaries. If the CSS control that look, any type of divider will be
recommended.

So far, I was adding spaces to separate text.

Hopefully this can be fixed at the same time.

Jacob

**Comment by philippjfr** [comment]
Okay I've made a PR with a number of CSS fixes, which I'll merge shortly. If you have other issues a PR to adjust the CSS defined in ``Markdown._css_style`` would be appreciated.
