### ISSUE TITLE
Interact should accept tuple of min, max, and value as input

### ISSUE THREAD

**Issue by jsignell** [pyviz/panel#333]
At the moment interact only supports passing value OR (min, max). It would be very helpful to be able to pass all three. For context - this came up in the context of making widgets from intake user parameters which have default values in addition to min, and max.

**Comment by jbednar** [comment]
Definitely.  PR?

**Comment by jsignell** [comment]
The problem is that a tuple of three currently means (min, max, step) so either the value could be the 4th item, or the meaning of a 3 tuple would change.

**Comment by jbednar** [comment]
It would need to be the 4th item, then.

**Comment by jsignell** [comment]
For clarity - it would work just as well for my use case if there were a way to set function defaults from a dict. 

This works as expected:
```python
@interact(year=(2017, 2018), month=(1, 12), day=(1, 31))
def day(year=2018, month=1, day=1):
    return cat.anaconda_package_data_by_day(**locals())
```

The issue is that those default values are in a dict and I don't know how to extract them into the function definition.
