### ISSUE TITLE
_pending_writes should be non-None when we have a document lock

### ISSUE THREAD

**Issue by xavArtley** [pyviz/panel#344]
```python
import panel as pn
import tkinter as tk
from threading import Thread
from panel.io import get_server
from functools import partial

slider = pn.widgets.FloatSlider()

import asyncio


def get_server_in_thread(**kwargs):
    asyncio.set_event_loop(asyncio.new_event_loop())
    get_server(**kwargs)

class Display():

    def __init__(self):
        Thread(target=partial(get_server_in_thread,panel=slider,start=True,show=True,port=5010)).start()
        self.root = tk.Tk()
        self.slider = tk.Scale(self.root, from_=0., to=1., resolution=0.1,
                               orient=tk.HORIZONTAL, command=self.on_slider_change)
        self.slider.pack()
        self.root.mainloop()


    def on_slider_change(self, event):
        slider.value = float(event)

display = Display()
```

![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/18531147/55243360-5f7dad80-523f-11e9-93c9-5478be26b5a5.gif)

**Comment by xavArtley** [comment]
May be a windows related issue

**Comment by philippjfr** [comment]
Thanks, I'll try to set this up on my windows machine.

**Comment by xavArtley** [comment]
This is call stacks, left when there is error, right when the update succeed
![error](https://user-images.githubusercontent.com/18531147/55244399-660d2480-5241-11e9-93e7-604d959a9bea.png)
It seems like the callback is called from the wrong thread (main)

**Comment by philippjfr** [comment]
That's odd, I'd expect this to schedule an event on the IO loop which should then be run on the thread:

```
    def on_slider_change(self, event):
        slider.value = float(event)
```

What I think is happening is that for whatever reason ``pn.state.curdoc`` is defined, which causes it to skip the scheduling. Could you insert some print statements panel.io.state.curdoc and see what is setting the curdoc?

**Comment by philippjfr** [comment]
When I try this locally (where it is working) ``pn.state.curdoc`` is always defined when the JS slider is dragged and is None when the Tk slider is dragged, which is what I'd expect.

**Comment by xavArtley** [comment]
![Capture](https://user-images.githubusercontent.com/18531147/55246963-b3d85b80-5246-11e9-9556-ddde9ee41f8b.PNG)

**Comment by xavArtley** [comment]
Mine is always state00002

**Comment by philippjfr** [comment]
Not looking for the value of state itself, it's the ``curdoc`` I'm interested in. It should be none whenever the tk slider is dragged.

**Comment by xavArtley** [comment]
ah ok so it's none as spe
![image](https://user-images.githubusercontent.com/18531147/55247280-788a5c80-5247-11e9-9a0f-b1d51ecb2d54.png)

**Comment by philippjfr** [comment]
That's bizarre, I don't know how the error can occur if it is None. Here is the relevant code, if it is None it should go into the else branch but it seems to be going into the first branch:

```python
if comm or doc is state.curdoc:
    self._update_model(events, msg, root, model, doc, comm)
    if comm and 'embedded' not in root.tags:
        push(doc, comm)
else:
    cb = partial(self._update_model, events, msg, root, model, doc, comm)
    doc.add_next_tick_callback(cb)
````

**Comment by philippjfr** [comment]
What I can try to do is record the thread id, and if we're on the wrong thread it would force it to go down the else branch.

**Comment by xavArtley** [comment]
Indeed if I force using the else part there is no problem
