### ISSUE TITLE
How to export embedded output using components?

### ISSUE THREAD

**Issue by ericmjl** [pyviz/panel#346]
My use case backing this question is to take a holomap from HoloViews, encapsulate it in a pn.panel, and then serve that up inside a Flask app.

A code snippet that I have thus far, which doesn't work, is:

```python
    scores_bar = scores_ds.to(
        hv.Bars, ["variable", "reviewer_id"], ["value"]
    ).opts(width=600)

    plot = pn.panel(scores_bar)

    # hv_scores_bar = renderer.get_plot(plot).state
    script, div = components(plot)

    return render_template("scores.html.j2", script=script, div=div)
```

Everything renders correctly in a Jupyter notebook, but I'm stuck on the Flask embedding part.

I think I might be lacking some knowledge of the internal data model, but I would love to learn how to fix this!

**Comment by philippjfr** [comment]
Also a good opportunity to document embedding properly.

**Comment by philippjfr** [comment]
The correct code here is:

```python
script, div = components(plot.get_root())
render_template("scores.html.j2", script=script, div=div)
```
