### ISSUE TITLE
Panel and Holoviews extensions

### ISSUE THREAD

**Issue by kcpevey** [pyviz/panel#356]
I had previously been using `hv.extension('bokeh')` to render my plots with bokeh. That also succeeded in giving me the panel visualization.   
  
Now, with the latest master: `panel='0.5.0a5.post28+g5a1e229'` I have to load both the hv.extension AND the pn.extension in order to view panel AND my plots properly:  
  
```
import holoviews as hv
hv.extension('bokeh')
import panel as pn
pn.extension()
```  
  
Is there a way to load them both at the same time?

**Comment by philippjfr** [comment]
Thanks for filing this issue, I meant to look at this today. I had explicitly disabled rendering if the extension isn't loaded but this should apply to both the hv and panel extension.
