### ISSUE TITLE
Incomplete output in JupyterLab and Notebooks 

### ISSUE THREAD

**Issue by yajiez** [pyviz/panel#369]
When using `pn.pane.Markdown` the height of output is very small unless specify a fixed height value, please see below:

<img src=https://user-images.githubusercontent.com/733113/55667756-8d26b000-5858-11e9-884a-9011fcda6495.png width='66%'></img>

Also, when using `pn.Column` the output is also incomplete and there is no way to specify the height for the `Column`:

<img src=https://user-images.githubusercontent.com/733113/55667796-07efcb00-5859-11e9-96d3-01660269124f.png width='66%'></img>

I'm using JupyterLab 0.35.3 and Panel 0.4.0 from conda-forge. Similar behavior in the notebook mode.

Thanks!

**Comment by philippjfr** [comment]
I would not recommend using panel 0.4.0 at this point. The new version 0.5.0 is out on conda now and will be on pypi next week we hope.

**Comment by yajiez** [comment]
I have tried update panel but just realised I should use `pyviz` channel instead of `conde-forge`. 
Thanks!

**Comment by philippjfr** [comment]
Yes, we'll hopefully have everything up on conda-forge and even defaults in the next couple of weeks.
