### ISSUE TITLE
v0.5.0 not on PyPI

### ISSUE THREAD

**Issue by banesullivan** [pyviz/panel#370]
v0.5.0 is not on PyPI https://pypi.org/project/panel/#history

**Comment by stonebig** [comment]
Apparently, the team is waiting for Bokeh-1.1.0 to land on pypi first. That should happen this week.

**Comment by banesullivan** [comment]
Ah thanks, @stonebig!

**Comment by philippjfr** [comment]
Yes, this is an unfortunate artifact of the fact that we had urgent deadlines to meet and were forced to push out the conda release early. I'll likely tag a 0.5.1 once bokeh 1.1.0 is released, which will appear on both conda and PyPI.

**Comment by banesullivan** [comment]
> I'll likely tag a 0.5.1 once bokeh 1.1.0 is released

Awesome! I look forward to `v0.5.1` for [`vtki`](http://docs.vtki.org) users
