### ISSUE TITLE
Initializing VTK extension takes a while

### ISSUE THREAD

**Issue by banesullivan** [pyviz/panel#371]
Initializing the VTK extension:

```py
import panel
print('Initializing panel...')
panel.extension('vtk')
print('Done.')
```

Takes almost a minute+ (when running on Binder) and ~10-30 seconds locally. The lag on Binder is concerning as new users might wonder why it isn't responding and close out of the page.

Check out this binder project to experience the lag: [![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/vtkiorg/vtki-examples/master)

**Comment by ea42gh** [comment]
`import panel
%timeit panel.extension('vtk')
`
on my local system results in
86.9 ms ± 10.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

**Comment by banesullivan** [comment]
See the examples below for my local machine and a remote machine. Perhaps there's a way to handle this set up for the whole environment without running upon import?

## Local Machine

On my local system:
```
Darwin : OS
     8 : CPU(s)
 6.4.0 : IPython
 7.4.2 : ipywidgets
 0.5.0 : panel
```

```py
import time
start = time.time()
import panel
print('Initializing panel...')
panel.extension('vtk')
end = time.time()
print('{}'.format(end - start))
```
```txt
Initializing panel...
15.53006911277771
```

Then separately (after relaunching a new kernel), 

```py
import panel
%timeit panel.extension('vtk')
```
```txt
32.2 ms ± 5.22 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

Something isn't right with `timeit`...

## Remote Machine

Then on the binder link that I shared in the original post:

```py
import time
start = time.time()
import panel
print('Initializing panel...')
panel.extension('vtk')
end = time.time()
print('{}'.format(end - start))
```
```txt
Initializing panel...
57.85710263252258
```

**Comment by xavArtley** [comment]
Depending how you install panel. Extensions can be already compiled or not. When compiled in panel/models you should have some .json corresponding to the .ts file. If you have not these json each time you invoke pn.extension the ts file will be compiled

**Comment by banesullivan** [comment]
How could I compile this at the time of install?

Currently I just install panel using pip (and bokeh from the conda dev channel):

```bash
pip install git+git://github.com/pyviz/panel@v0.5.0
```

**Comment by xavArtley** [comment]
You have to clone with git cd in it and use python setup.py install

**Comment by xavArtley** [comment]
Panel 0.5 is on conda on pyviz/label/dev i think

**Comment by banesullivan** [comment]
> Panel 0.5 is on conda on pyviz/label/dev i think

Ah! That's a big help!

**Comment by banesullivan** [comment]
Thanks, @xavArtley - using the deployed version on `pyviz/label/dev` sped it up!
