### ISSUE TITLE
Incorrect Pipeline._stage after failed next stage

### ISSUE THREAD

**Issue by kcpevey** [pyviz/panel#373]
Supposing something goes wrong in loading the next of the pipeline - the user gets the error `Next stage raised following error:`. And the pipeline doesn't progress to the next stage, user remains on the same stage.  
  
If you check pipeline._state it will correctly indicate that the stage has not changed, however, if you check pipeline._stage it will incorrectly indicate that the stage has progressed to the next.   
  
I would expect pipeline._stage to always represent what is visualized in the panel, but in this case, it does not.

**Comment by philippjfr** [comment]
Now I'm confused, in #375 I made sure that it would correctly revert ``pipeline._state`` since ``pipeline._stage`` seemingly was already handled correctly but you seem to be indicating that actually the opposite was happening. Will have to look at this again.

**Comment by kcpevey** [comment]
Ah. I'm on 0.5.0. Maybe I need to upgrade and try again?

**Comment by philippjfr** [comment]
Well no, I only just made the fix and by the sound of it I made the wrong fix.

**Comment by kcpevey** [comment]
I updated to panel master ('0.5.1') and this is fixed. So apparently it was already fixed in master and your fix reversed it back to broken. Sorry about that, I should have tested on master.

**Comment by philippjfr** [comment]
I'm super confused now, master and 0.5.1 are identical, so you're saying this is fixed now? In which case my fix was correct.

**Comment by kcpevey** [comment]
'Fixed' might have been (was) an inaccurate term. I dug a little deeper and realized that the behavior has changed.   
  
From my usecase:
On the second stage, before trying to proceed to stage 3:  
```
print(pipeline._stage)
print(pipeline._state)
1
<HurricaneView HurricaneView04546>
```
After clicking `next` and getting an error warning, my UI remains on stage 2 and i get this:
```
print(pipeline._stage)
print(pipeline._state)
1
ParamMethod(method)
```
Actually running `pipeline._state` now results in a VISUALIZATION of the stage, not the text description of the `<HurricaneView HurricaneView04546>` instance I was expecting.
