### ISSUE TITLE
[vtk] keypress event bug

### ISSUE THREAD

**Issue by banesullivan** [pyviz/panel#378]
When using `panel`'s new VTK functionality in a Joptyer notebook, the panel listens to key events outside of its scope. 

When writing new code in a different cell, buttons like `v` and `s` alter the scene - this is unexpected behavior. See example below using `vtki` which sends its renderer to panel's VTK code:

![ezgif com-video-to-gif-3](https://user-images.githubusercontent.com/22067021/56014852-24a25d80-5cb4-11e9-991e-2f48bae53b61.gif)

**Comment by xavArtley** [comment]
I don't know if we can do something about it. However we sould document the key bindings somwhere.

**Comment by banesullivan** [comment]
> we should document the key bindings somewhere.

I definitely agree that they should be documented - I only discovered `v` for vertex/point representation and `s` for surface by typing code slowly.

> I don't know if we can do something about it.

I think this is a `panel` issue. If you display a VTKjs rendering via HTML this behavior is not experienced:

```py

from IPython.core.display import display, HTML
display(HTML(
'''
<div style="position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; height: auto;">
        <iframe src="http://volcano.pvgeo.org" frameborder="0" allowfullscreen style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;"></iframe>
    </div>
'''))
```


![ezgif com-video-to-gif-5](https://user-images.githubusercontent.com/22067021/56016089-6c2ae880-5cb8-11e9-8e41-15e4639a3b5c.gif)


`panel` is on top, HTML is bottom. Note that the HTML output is simply pointing to this url: http://volcano.pvgeo.org which has keyboard shortcuts when on the webpage but not in the notebook

**Comment by banesullivan** [comment]
The other thing to note is that this is causing a noticeable lag when typing `s`, `v`, `w`, or other keys that affect the `panel` scene.

If a notebook has more than a few VTK panel scenes, then adding new code with the letters `v`, `s`, or `w` will heavily lag the notebook (and be quite an annoyance). For example, typing `examples.download_st_helens().warp_by_scalar().plot()` almost a minute after loading up 5 other scenes:

![ezgif com-video-to-gif-6](https://user-images.githubusercontent.com/22067021/56016659-3edf3a00-5cba-11e9-900d-6c681be66a14.gif)

**Comment by xavArtley** [comment]
key events are set by vtkjs interactor:
https://github.com/Kitware/vtk-js/blob/cc48e943037e0ed980c5e370b0e716df3309a5b2/Sources/Rendering/Core/RenderWindowInteractor/index.js#L214-L222

They are attached to the document body so it's not a panel bug.
What I can try to do is to add an option to activate or deactivate keybindings

**Comment by xavArtley** [comment]
Does something like this would be sufficient?

![ezgif com-video-to-gif (7)](https://user-images.githubusercontent.com/18531147/56023289-d91c9d80-5d0d-11e9-95c3-d221cdb9963e.gif)

**Comment by philippjfr** [comment]
Yeah, I don't see a better solution either. The iframe example doesn't capture the keybindings because that's how iframe's work, anything embedded in a page will. If VTK had some concept of giving focus to the view window maybe we could make sure it only responds if the viewing window has been selected.

**Comment by xavArtley** [comment]
Actually I don't if the best is not just to remove all keybindings

**Comment by banesullivan** [comment]
I've installed `panel` from the master branch and this still isn't resolved. Am I missing something?

**Comment by xavArtley** [comment]
Did you recompiled extensions?
pip install git+... will not recompile extensions.
you need to run a python setup.py install or develop

**Comment by xavArtley** [comment]
@philippjfr shouldn't we subclass `distutils.command.build.build` in setup.py ? with something like :
```python
class CustomBuildCommand(build):
    """Custom installation for build mode."""

    def run(self):
        try:
            from panel.compiler import build_custom_models
            print("Building custom models:")
            build_custom_models()
        except ImportError as e:
            print("Custom model compilation failed with: %s" % e)
        build.run(self)
```

**Comment by philippjfr** [comment]
@xavArtley You're probably right, I don't know enough about how distutils works to know for sure. Do the `develop` and `install` commands both call the `build` command, i.e. could it replace them?

**Comment by banesullivan** [comment]
@xavArtley, thanks for the tip! I had some build artifact lying around from a previous conda install after I cloned the repo that needed to be cleaned up - all good now!
