### ISSUE TITLE
@param.depends usage

### ISSUE THREAD

**Issue by kcpevey** [pyviz/panel#381]
I have some classes which contain other classes. I suspect what I'm wanting to do is not possible, and I'm looking for a workaround. I want to do something like this:

```
class simulation(param.Parameterized):
    color = param.ObjectSelector(default='red', objects=['red','green'])
    num = param.Number(default=0.4, bounds=(0,3))

class Stage2(param.Parameterized):

    c = param.Number(default=5, precedence=-1, bounds=(0, None))

    exp = param.Number(default=0.1, bounds=(0, 3))
    
    sim_selector = param.Dict(default=dict)
    
    
    def __init__(self, **params):
        super(Stage2, self).__init__(**params)
        
        sim_selector['sim1'] = simulation()
        sim_selector['sim2'] = simulation()
    
    @param.depends('c', 'exp', 'sim_selector['sim2'].color')
    def view(self):
        return pn.pane.LaTeX('${%s}^{%s}={%.3f}$' % (self.c, self.exp, self.c**self.exp),
                             style={'font-size': '2em'})

    def panel(self):
        return pn.Row(self.param, self.view)
```
However, since @param.depends takes a string, `'sim_selector['sim2'].color'` will of course not evaluate properly. It seems like my only real option here is to depend on `sim_selector` which will trigger with ANY changes to the simulation, not just `color`. Is there a better solution?

**Comment by mdk73** [comment]
See, if this suits your needs:

```python
import param
import panel as pn
pn.extension()
param.__version__, pn.__version__

class Simulation(param.Parameterized):
    color = param.ObjectSelector(default='red', objects=['red','green'])
    num = param.Number(default=0.4, bounds=(0,3))

class Stage2(param.Parameterized):
    c = param.Number(default=5, precedence=-1, bounds=(0, None))
    exp = param.Number(default=0.1, bounds=(0, 3))
    sim1 = Simulation()
    sim2 = Simulation()
    sim_selector = param.ObjectSelector(default= sim2, objects=[sim1, sim2])
    
    @param.depends('c', 'exp', 'sim2.color')
    def view(self):
        return pn.pane.LaTeX('${%s}^{%s}={%.3f}$' % \
                             (self.c, self.exp, self.c**self.exp),
                             style={'font-size': '2em'})

    def panel(self):
        return pn.Row(self.param, self.view)
    
test = Stage2()
test.panel()
```

![panel_issue381](https://user-images.githubusercontent.com/2737768/56563484-1dc8f400-65ac-11e9-9820-aeda9316b88f.png)

**Comment by jbednar** [comment]
`@param.depends('c', 'exp', 'sim_selector.color')` doesn't work?

**Comment by philippjfr** [comment]
You would definitely have to encapsulate the ``sim_selector`` object differently, ``depends`` definitely does not currently allow referencing dictionary values and I don't think it would be a good idea to support that since dictionaries are mutable and the Parameterized would not know when the values change.

**Comment by philippjfr** [comment]
I'm going to close this since it's really a usage a question and/or a feature request for param.

**Comment by philippjfr** [comment]
Maybe you really intended what @mdk73 described and want ``sim_selector`` to be an ObjectSelector instead of a ``param.Dict``?

**Comment by jbednar** [comment]
Oh, I was looking at @mdk73's code, not the original code.  My suggestion of `sim_selector.color` was meant for his version, where sim_selector is indeed an ObjectSelector as the name would indicate.

**Comment by philippjfr** [comment]
>My suggestion of sim_selector.color was meant for his version, where sim_selector is indeed an ObjectSelector as the name would indicate.

Yes in that version ``sim_selector.color`` is definitely the correct spelling.
