### ISSUE TITLE
Panel transforms plotly timestamps to numbers

### ISSUE THREAD

**Issue by abourrier** [pyviz/panel#382]
Create a plotly time series curve:
```python
import numpy as np
import pandas as pd
import panel as pn
import plotly.offline as py
import plotly.graph_objs as go

pn.extension("plotly")
py.init_notebook_mode()

index = pd.date_range(start="2019-01-01", end="2019-02-01", freq="1D")
data = np.random.randn(index.size)
traces = [go.Scatter(x=index, y=data)]
```
`py.iplot(traces)` correctly displays it:
![newplot](https://user-images.githubusercontent.com/22977572/56109036-1d4ab080-5f4f-11e9-8784-1d27bbb63dd8.png)
`pn.panel(traces)` converts the timestamps to numbers:
![newplot2](https://user-images.githubusercontent.com/22977572/56109062-34899e00-5f4f-11e9-968c-8c09489b0eb7.png)

Tested with panel 0.5.1 and plotly 3.7.1

**Comment by philippjfr** [comment]
Suspect it has something to do with the serialization. Panel uses bokeh's JSON transforms, which are probably casting the datetimes to an integer representation not recognized by Plotly, should be a reasonably straightforward fix I hope.

**Comment by hcoohb** [comment]
I confirm the issue is still present with panel 0.6.0 and plotly 3.10.0

**Comment by a-recknagel** [comment]
@hcoohb Running your test case on 30774155d010c6b9f9d6e9f9fb5753466356704b gives me this:

![Screenshot from 2019-10-12 13-24-42](https://user-images.githubusercontent.com/2063412/66700685-b175b480-ecf3-11e9-82ec-ad389b646e7c.png)

I hope any edge cases will also be handled.
