### ISSUE TITLE
Expose scroll

### ISSUE THREAD

**Issue by jsignell** [pyviz/panel#383]
To get scroll in a panel object you currently have to use css classes. This looks like:

```python
import panel as pn

css = """
.widget-box {
  overflow: scroll;
}
"""

pn.extension(raw_css=[css])

pn.Column(
    pn.widgets.FloatSlider(name='Number', width=200, ),
    pn.widgets.Select(name='Fruit', options=['Apple', 'Orange', 'Pear']),
    pn.widgets.Button(name='Run'),
css_classes=['widget-box'], width=100, height=50, background='#f0f0f0')
```

I propose we add overflow as a kwarg in all panel objects or possibly just all pane and layout options.

**Comment by philippjfr** [comment]
I'm +1 on this, I think there are generally useful options which could be implemented in CSS and exposed as parameters on the ``Layoutable`` baseclass.
