### ISSUE TITLE
Widgets are not shown in notebook

### ISSUE THREAD

**Issue by mdk73** [pyviz/panel#387]
With panel from the development channel (pyviz/label/dev) Toggles and panes are not shown in the notebook.

```python
import panel as pn
import panel.widgets as pnw
import holoviews as hv
import bokeh
pn.extension()
pn.__version__, hv.__version__, bokeh.__version__

button = pnw.Toggle(name='t1', width=50)
button

pn.Row(button)

pn.extension('katex')
pn.pane.LaTeX('${a} * {b} = {c}$\n${a}^{{{b}}} = {d}$'\
              .format(a=1, b=2, c=3, d=4))
```

screenshot notebook (panel 0.5.1)
![widgets panel 0 5 1](https://user-images.githubusercontent.com/2737768/56302922-1f716280-613b-11e9-95ff-feb613b9ced3.png)

Screenshot notebook with the latest panel release (0.4.0):
![widgets panel 0 4 0](https://user-images.githubusercontent.com/2737768/56303089-79722800-613b-11e9-8983-23d707504126.png)

:

**Comment by mdk73** [comment]
This issue is probably not related to panel 0.5.1. While the original notebook shown above still does not display widgets, the same code is working as expected if I create a new notebook and copy the code into the cells and run the new notebook.

**Comment by philippjfr** [comment]
Yes, this is likely related to pyviz_comms changes. I'd suggest clearing old notebooks, saving and reloading the page before rerunning them.
