### ISSUE TITLE
The Pane of a DynamicMap scatter plot doesn't show the size correctly for the first time

### ISSUE THREAD

**Issue by ruoyu0088** [pyviz/panel#390]
Here is the code

```
import pandas as pd
import numpy as np
import hvplot.pandas

n = 200
df = pd.DataFrame(dict(
    x=np.random.randn(n), 
    y=np.random.randn(n), 
    s=np.random.uniform(5, 20, n),
    c=np.random.randint(0, 4, size=n)))
plot = df.hvplot.scatter(x="x", y="y", s="s", groupby="c")
pn.Pane(plot)
```

which shows

![chrome_2019-04-19_11-51-01](https://user-images.githubusercontent.com/826871/56402958-65910800-629a-11e9-80fc-40ee5684d3ad.png)

the points are the same size

drag the slider and move the back to 0

![chrome_2019-04-19_11-51-16](https://user-images.githubusercontent.com/826871/56402988-7fcae600-629a-11e9-9024-de200b26f12f.png)

**Comment by philippjfr** [comment]
Can't reproduce this, whatever was causing this seems to have been fixed.
