### ISSUE TITLE
Pipeline stages are not syncronized

### ISSUE THREAD

**Issue by mdk73** [pyviz/panel#393]
This is a duplicate of https://github.com/pyviz/panel/issues/360, but with a much shorter test code, and tested against the current developement version via ```conda install -c pyviz/label/dev panel```.
Variable ```inp``` in ```stage2``` should reflect changes in variable ```out``` in ```stage1```, but it is not.

```python
import param
import panel as pn
pn.extension()
param.__version__, pn.__version__

class Stage1(param.Parameterized):
    out = param.Number(default=5, bounds=(0, 10))
    
    @param.output(('out', param.Number))
    def output(self):
        return self.out

    def panel(self):
        return pn.Row(self.param)

class Stage2(param.Parameterized):
    inp = param.Number(default=5, bounds=(0, None))

    def panel(self):
        return pn.Row(self.param)

stage1 = Stage1()
stage2 = Stage2(inp=stage1.output())

pipeline = pn.pipeline.Pipeline()
pipeline.add_stage('Stage 1', stage1)
pipeline.add_stage('Stage 2', stage2)
pn.Row(stage1.panel(), stage2.panel())

stage1.output()
```

![pipeline_test_case](https://user-images.githubusercontent.com/2737768/56564691-ef004d00-65ae-11e9-8e11-d4f678bb6242.png)

**Comment by philippjfr** [comment]
This isn't how Pipelines are supposed to work, first of all pipelines will only work when using the ``pipeline.layout`` object. Secondly the name of an output of a stage must match the name of an input parameter of the next stage.

**Comment by mdk73** [comment]
Thanks, so totally misunderstood the idea behind pipelines. So the concept behind pipelines is something similar to tabs in other frameworks?

**Comment by philippjfr** [comment]
It's kind of like an ordered set of tabs I suppose, the original goal for pipelines was that they could be used to express any directed acyclic graph of different stages, but we've not yet had the time to fully implement that. I kind of regret merging pipelines as early as we did.

**Comment by jbednar** [comment]
I think we should simply mark pipelines as an experimental feature, useful but likely to change. In any case, the change needed for this particular case is simply to rename the input parameter to match the output of the previous stage, right?  So this seems like a small fix to make, not a big misunderstanding, to me!

**Comment by philippjfr** [comment]
No, the misunderstanding was that you could add stages to a pipeline and
they would then be intrinsically linked in some way. How it actually works
is that they are only linked when displayed as part of the pipeline object.
