### ISSUE TITLE
raw_css not working

### ISSUE THREAD

**Issue by jsignell** [pyviz/panel#397]
On panel 0.5.1, this seems to no longer be working:

```python
pn.extension(raw_css="""
.scrolling {
  overflow: scroll;
}
""")
pn.pane.Str('lfdblafdlsa', width=40, height=20, css_classes=['scrolling'])
```

The scrolling class gets populated on the pane, but the css doesn't seem to be available.

**Comment by philippjfr** [comment]
raw_css should be a list, should definitely warn or error though
