### ISSUE TITLE
matplotlib chart not updating 

### ISSUE THREAD

**Issue by robbie-sp** [pyviz/panel#399]
Seem to have an issue similar to #159.

Using example from introduction in [docs](https://panel.pyviz.org/user_guide/Introduction.html) the chart renders with the widgets but the chart does not update when widget values are changed.

The hvplot chart example does update as expected.

I read the advice for MPL plots in the [FAQs ](https://panel.pyviz.org/FAQ.html) but this has not helped.

Code running in a single cell using Jupyter lab with panel extension installed.

```python
import numpy as np, pandas as pd, matplotlib.pyplot as plt
import panel as pn
import matplotlib as mpl
mpl.use('Agg')  # from FAQs

def mplplot(df, **kwargs):
    fig = df.plot().get_figure()
    plt.close(fig)
    return fig

def sine(frequency=1.0, amplitude=1.0, n=200, view_fn=mplplot):
    xs = np.arange(n)/n*20.0
    ys = amplitude*np.sin(frequency*xs)
    df = pd.DataFrame(dict(y=ys), index=xs)
    return view_fn(df, frequency=frequency, amplitude=amplitude, n=n)

pn.interact(sine)
```
Thanks in advance for any help.

**Comment by philippjfr** [comment]
Could you report the panel, param and pyviz_comms versions? I can't reproduce any issue.

**Comment by robbie-sp** [comment]
panel 0.4.0
param 1.8.2
pyviz_comms 0.7.2

using conda environment with nb_conda to connect Jupyter lab to kernel
Jupyter lab 0.35.4

Installing the jupyter lab extension generated quite a few warnings:

> Node v11.11.0
> 
> > C:\Users\u006256\AppData\Local\Continuum\miniconda3\npm.CMD pack @pyviz/jupyterlab_pyviz
> npm notice
> npm notice package: @pyviz/jupyterlab_pyviz@0.7.1
> npm notice === Tarball Contents ===
> npm notice 1.3kB package.json
> npm notice 1.5kB LICENSE.txt
> npm notice 1.9kB README.md
> npm notice 64B   lib/index.d.ts
> npm notice 151B  lib/index.js
> npm notice 556B  lib/manager.d.ts
> npm notice 1.4kB lib/manager.js
> npm notice 577B  lib/plugin.d.ts
> npm notice 1.5kB lib/plugin.js
> npm notice 1.9kB lib/renderer.d.ts
> npm notice 9.3kB lib/renderer.js
> npm notice 419B  lib/widgets.d.ts
> npm notice 5.6kB lib/widgets.js
> npm notice === Tarball Details ===
> npm notice name:          @pyviz/jupyterlab_pyviz
> npm notice version:       0.7.1
> npm notice filename:      pyviz-jupyterlab_pyviz-0.7.1.tgz
> npm notice package size:  7.5 kB
> npm notice unpacked size: 26.3 kB
> npm notice shasum:        adbfbf1a134bb3705bcf8467f1d42655cd8e313e
> npm notice integrity:     sha512-GL73B1sGl9TQV[...]QyYLyb7PR8BCA==
> npm notice total files:   13
> npm notice
> pyviz-jupyterlab_pyviz-0.7.1.tgz
> Node v11.11.0
> 
> > node C:\Users\u006256\AppData\Local\Continuum\miniconda3\lib\site-packages\jupyterlab\staging\yarn.js install
> yarn install v1.9.4
> info No lockfile found.
> [1/5] Validating package.json...
> [2/5] Resolving packages...
> warning @jupyterlab/application > @jupyterlab/apputils > react > fbjs > core-js@1.2.7: core-js@<2.6.5 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
> warning css-loader > cssnano > autoprefixer > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
> warning css-loader > cssnano > postcss-merge-rules > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
> warning css-loader > cssnano > postcss-merge-rules > caniuse-api > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
> [3/5] Fetching packages...
> (node:6952) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
> info fsevents@1.2.8: The platform "win32" is incompatible with this module.
> info "fsevents@1.2.8" is an optional dependency and failed compatibility check. Excludingit from installation.
> [4/5] Linking dependencies...
> warning "@jupyterlab/vdom-extension > @nteract/transform-vdom@1.1.1" has incorrect peer dependency "react@^15.6.1".
> warning "@jupyterlab/vega4-extension > vega-embed > vega-themes@2.3.0" has unmet peer dependency "vega@*".
> [5/5] Building fresh packages...
> success Saved lockfile.
> Done in 73.85s.
> > node C:\Users\u006256\AppData\Local\Continuum\miniconda3\lib\site-packages\jupyterlab\staging\yarn.js run build
> yarn run v1.9.4
> $ webpack
> Hash: 8dd6b3c2f141b905ad42
> Version: webpack 4.12.2
> Time: 21266ms
> Built at: 04/25/2019 4:12:39 PM
>                                    Asset       Size        Chunks             Chunk Names
>     674f50d287a8c48dc19ba404d20fe713.eot    162 KiB                [emitted]
>   af7ae505a9eed503f8b8e6982036873e.woff2   75.4 KiB                [emitted]
>     912ec66d7572ff821749319396470bde.svg    434 KiB                [emitted]
>    fee66e712a8a08eef5805a46892932ad.woff   95.7 KiB                [emitted]
>     b06871f281fee6b241d60582ae9369b9.ttf    162 KiB                [emitted]
>             main.77e6939885d737629c57.js   55.2 KiB          main  [emitted]  main
>                0.cc98107762fcc28532b3.js    4.5 KiB             0  [emitted]
>             vega.91b98e783d16fd1b9e23.js  519 bytes          vega  [emitted]  vega
>     vendors~main.bd6abc9d8918027424a5.js   8.51 MiB  vendors~main  [emitted]  vendors~main
>     vendors~vega.44c7b7e144bbd288b894.js   2.95 MiB  vendors~vega  [emitted]  vendors~vega
>                1.055322dcf6c2bb19185f.js    888 KiB             1  [emitted]
>         main.77e6939885d737629c57.js.map   64.3 KiB          main  [emitted]  main
>            0.cc98107762fcc28532b3.js.map   5.73 KiB             0  [emitted]
>         vega.91b98e783d16fd1b9e23.js.map  251 bytes          vega  [emitted]  vega
> vendors~main.bd6abc9d8918027424a5.js.map   9.83 MiB  vendors~main  [emitted]  vendors~main
> vendors~vega.44c7b7e144bbd288b894.js.map    2.3 MiB  vendors~vega  [emitted]  vendors~vega
>            1.055322dcf6c2bb19185f.js.map   1.04 MiB             1  [emitted]
>                               index.html   1.54 KiB                [emitted]
> Entrypoint main = vendors~main.bd6abc9d8918027424a5.js vendors~main.bd6abc9d8918027424a5.js.map main.77e6939885d737629c57.js main.77e6939885d737629c57.js.map
>  [0] multi whatwg-fetch ./build/index.out.js 40 bytes {main} [built]
>  [ANye] ./build/index.out.js 36.7 KiB {main} [built]
>  [yLpj] (webpack)/buildin/global.js 489 bytes {vendors~main} [built]
>  [1] vertx (ignored) 15 bytes {main} [optional] [built]
>  [RnhZ] ./node_modules/moment/locale sync ^\.\/.*$ 2.88 KiB {main} [optional] [built]
>  [YuTi] (webpack)/buildin/module.js 497 bytes {vendors~main} [built]
>  [eTbV] ./node_modules/codemirror/mode sync ^\.\/.*\.js$ 2.78 KiB {0} [built]
>  [2] util (ignored) 15 bytes {main} [built]
>  [4] buffer (ignored) 15 bytes {main} [optional] [built]
>  [5] crypto (ignored) 15 bytes {main} [optional] [built]
>  [6] readable-stream (ignored) 15 bytes {main} [built]
>  [7] supports-color (ignored) 15 bytes {main} [built]
>  [8] chalk (ignored) 15 bytes {main} [built]
> [10] node-fetch (ignored) 15 bytes {vega} [built]
> [11] fs (ignored) 15 bytes {vega} [built]
>     + 2469 hidden modules
> 
> WARNING in d3-array
>   Multiple versions of d3-array found:
>     1.2.4 ./~/d3-scale/~/d3-array from ./~/d3-scale/~/d3-array\src\index.js
>     2.0.3 ./~/d3-array from ./~/d3-array\src\index.js
> 
> 
> WARNING in vega-lite
>   Multiple versions of vega-lite found:
>     2.5.1 ./~/vega-lite\build\src from ./~/vega-lite\build\src\compile\selection\selection.js
>     2.6.0 ./~/vega-lite\build from ./~/vega-lite\build\src\index.js
> 
> Check how you can resolve duplicate packages:
> https://github.com/darrenscerri/duplicate-package-checker-webpack-plugin#resolving-duplicate-packages-in-your-bundle
> 
> Child html-webpack-plugin for "index.html":
>      1 asset
>     Entrypoint undefined = index.html
>     [KTNU] ./node_modules/html-loader!./templates/partial.html 567 bytes {0} [built]
>     [YuTi] (webpack)/buildin/module.js 497 bytes {0} [built]
>     [aS2v] ./node_modules/html-webpack-plugin/lib/loader.js!./templates/template.html 1.22 KiB {0} [built]
>     [yLpj] (webpack)/buildin/global.js 489 bytes {0} [built]
>         + 1 hidden module
> Done in 29.61s.

**Comment by philippjfr** [comment]
Panel 0.4.0 and param 1.8.2 are both outdated, the latest versions are 0.5.0 and 1.9.0 respectively.

**Comment by robbie-sp** [comment]
sorry - I just realised that myself and went to close the ticket.
I only installed Panel a week ago so not sure it and it was so old.
Can confirm it works as expected once panel updated to 0.5.0

Sorry for wasting your time.

**Comment by philippjfr** [comment]
No worries, thanks for following up.
