### ISSUE TITLE
Order of params not respected when using panel==0.5.1, param==1.9.0

### ISSUE THREAD

**Issue by rs2** [pyviz/panel#403]
## Env
```
- panel=0.5.1
- param=1.9.0
```

## Symptom
E.g. when running https://github.com/pyviz/panel/blob/master/examples/user_guide/Param.ipynb the order of widgets gets inverted:
![image](https://user-images.githubusercontent.com/4407787/56823294-5a664b00-684b-11e9-89fc-f1a5de816f69.png)

## Expected
The order should be phase, frequency as per the screenshot in [documentation](https://panel.pyviz.org/user_guide/Param.html).

**Comment by jbednar** [comment]
Are you on Python2 or Python3?  The order is respected only on Python3, due to the underlying dictionary support in each language.  On Python2 you'll need to add explicit precedence values if you want to control the order.

**Comment by rs2** [comment]
@jbednar py35

**Comment by jbednar** [comment]
Ah, that's the problem.  Attribute order wasn't preserved in Python until [3.6](https://docs.python.org/3/whatsnew/3.6.html).  Nothing we can do about that but suggest to upgrade to Python 3.6 or 3.7.
