### ISSUE TITLE
pyct not a hard dependency so 'Getting Started' example does not work as intended

### ISSUE THREAD

**Issue by robbie-sp** [pyviz/panel#406]
As pyct is not a dependency installed by default when using conda so I get the following error when doing

```bash
panel examples

[full trace removed for brevity]

pkg_resources.DistributionNotFound: The 'pyct>=0.4.4' distribution was not found and is required by panel
```

After manually installing pyct with conda, the panel examples command works.

This may be hard for new users who try to follow the [Getting Started](https://panel.pyviz.org/index.html#getting-started) section of the documentation straight after installation.

using:
Linux on WSL
panel 0.5.1
pyviz_comms 0.7.2

Thanks

**Comment by jsignell** [comment]
I suspect that you installed from conda-forge, which is indeed missing the dependency. I opened a PR to fix that here https://github.com/conda-forge/panel-feedstock/pull/7. In the meantime, the package on the `pyviz` channel (`conda install -c pyviz panel`) does have the `pyct` dependency.

**Comment by jsignell** [comment]
It's been merged now.
