### ISSUE TITLE
default style not used

### ISSUE THREAD

**Issue by fedario** [pyviz/panel#412]
When I run the code below in a notebook, the output does not look like shown [here](https://panel.pyviz.org/user_guide/Components.html) (green and gray).
Instead the text is plain black. The same happens when served via `panel serve file.ipynb`

Maybe the default css is not loaded correctly?

```Python
import panel as pn
pn.extension()

pn.pane.Markdown("""
# H1
## H2
### H3
""")
```

pyviz packages:

```
colorcet                  2.0.1                      py_0    pyviz
datashader                0.7.0                      py_0    pyviz
holoviews                 1.12.2                     py_0    pyviz
hvplot                    0.4.0                      py_0    pyviz
panel                     0.5.1                      py_0    pyviz
param                     1.9.0                      py_0    pyviz
pyct                      0.4.6                      py_0    pyviz
pyct-core                 0.4.6                      py_0    pyviz
pyviz_comms               0.7.2                      py_0    pyviz
```

**Comment by jbednar** [comment]
I assume the green is from the theme for the website, which is green to match Panel's logo, and wouldn't expect the results in Jupyter or when served to match that.  You can select a theme using Bokeh's [theming](https://bokeh.pydata.org/en/latest/docs/reference/themes.html) or via CSS.

**Comment by philippjfr** [comment]
Right, panel does not have control over the CSS of the website it is embedded in so this is fully expected.

**Comment by fedario** [comment]
OK, thank you for the quick response.

Is it also possible to control the style of the widgets?

**Comment by philippjfr** [comment]
We probably need some docs on that front but the ``css_classes`` section [here](http://panel.pyviz.org/user_guide/Customization.html) should provide a start.
