### ISSUE TITLE
control on widget for parameterized instance

### ISSUE THREAD

**Issue by ghislainp** [pyviz/panel#416]
I'm using parametrized instance which is excellent, but I'd like more control on the widget autogenerated from it. Is there a way to indicate the callback_policy when declaring the parameters ? I guess not because of the strict separation between param and the UI.

So I tried  to set the callbac_policy after creation (a bit hacky solution), but this does not work.

My code (simplified):
```python
class Slope(param.Parameterized):
     slope = param.Number(0, label="Tilt angle (°)", bounds=(0, 30))
    aspect = param.Number(180, label="Aspect angle (°)", bounds=(0, 360))
    
panel = pn.Row(slope.param)

def set_slider_policy(parent):
    for child in parent:
        if isinstance(child, pn.widgets.FloatSlider):
            child.callback_policy = 'mouseup'  # <-------------- this has no effect
            child.bar_color='#ff0000'  # <--------- this works
        elif isinstance(child, Iterable):
            set_slider_policy(child)
            
set_slider_policy(panel)

panel.servable()
```

**Comment by jbednar** [comment]
I'm not sure whether that approach should be expected to work, but would it work to set the default `callback_policy` for all `FloatSliders`?  If so you should be able to do that with:

```
import panel.widgets
panel.widgets.FloatSlider.callback_policy = 'mouseup'
```

**Comment by ghislainp** [comment]
Thanks. I had also tried this option and thought it didn't work, but in 
fact it works well. I now realize that my problem has nothing to do with 
setting widget parameters, but is related to an open issue in bokeh 
about |callback_policy
|

|https://stackoverflow.com/questions/38375961/throttling-in-bokeh-application|

|
|

**Comment by philippjfr** [comment]
Yeah, unfortunately this issue will have to be handled and fixed upstream.
