### ISSUE TITLE
Bogus error message about VTK

### ISSUE THREAD

**Issue by jbednar** [pyviz/panel#429]
Users get a bizarre error message if they try to make a pane out of None:

![image](https://user-images.githubusercontent.com/1695496/57634822-ad3e4300-756b-11e9-89b7-13df0c065dc0.png)

I encountered it because of a bug elsewhere in my code that resulted in a parameter returning None rather than an actual value, but the error message was _not_ very helpful in tracking that down...

**Comment by jbednar** [comment]
I'd expect to see just the string "None", as a representation of None, just as strings, integers, and other Python types display themselves.

**Comment by jbednar** [comment]
And note that in some cases, depending on out of order execution, it looks like it actually _is_ trying to display None using VTK, even though I have never run `pn.extension("vtk")`:

![image](https://user-images.githubusercontent.com/1695496/57635396-a82dc380-756c-11e9-84d5-d6303453cbbc.png)

**Comment by kcpevey** [comment]
I've seen this error a lot since the VTK merge. It has generally happened to me when I had something coded wrong and panel was trying to make sense of it. Seems like it was defaulting back to vtk? I could never come up with a good idea of what was happening so I never made an issue.

**Comment by philippjfr** [comment]
The VTK pane applies check is probably catching None's for some reason, should be an easy fix.

**Comment by philippjfr** [comment]
Yeah, this is a pretty bad check:

```python
def applies(cls, obj):
        return (isinstance(obj, getattr(vtk, 'vtkRenderWindow', type(None))) or
                hasattr(obj, 'read') or (isinstance(obj, string_types) and obj.endswith('.vtkjs')))
```

**Comment by philippjfr** [comment]
Will catch NoneTypes and pretty much any file-like type.

**Comment by jbednar** [comment]
I imagine you can fix that easily enough. :-)  But regardless of the check, should we be expecting VTK objects to display themselves even without `pn.extension("vtk")`, but only sometimes?  That seems surprising to me as well.

**Comment by philippjfr** [comment]
>But regardless of the check, should we be expecting VTK objects to display themselves even without pn.extension("vtk"), but only sometimes?

Yes, they will but you will get a warning. That's expected behavior and less confusing for users than having it display sometimes unless you do something very specific they may never know about otherwise.

**Comment by jbednar** [comment]
It's expected that it will sometimes display, and sometimes give a warning, without changing any user code?  I can't quite tell when it displays and when I'll get a warning, but something about re-executing the same cell or the same notebook.  The warning is helpful, but it would be a lot easier to work with if it always warned or always worked, not some seemingly random switch between the two.

**Comment by philippjfr** [comment]
Hmm, I guess the problem currently is that the warning is based on whether the thing has been imported and it will have been imported after the first attempt. It should really warn if the model wasn't imported before running the extension, will have to think about that.

**Comment by jbednar** [comment]
Right; that's what I'm thinking.  Something to make the behavior predictable and repeatable will really help the user work with Panel, by keeping the user's mental model simple and straightforward.

**Comment by philippjfr** [comment]
Can just keep a list of custom models that were loaded on extension load time and if the current model isn't one of those it will warn.
