### ISSUE TITLE
Panel loading is too slow

### ISSUE THREAD

**Issue by henriqueribeiro** [pyviz/panel#453]
With the lastest panel version, loading it takes too long. Below is an example:

```python
%%time

import panel as pn
pn.extension()

display(pn.widgets.Button(name='Click me'))
```
I get the following times:
```
CPU times: user 1.03 s, sys: 871 ms, total: 1.9 s
Wall time: 25 s
```

**Comment by philippjfr** [comment]
Note that the issue is specific to the `pip` package which does not include the precompiled custom models.

**Comment by henriqueribeiro** [comment]
Yep, sorry, I forgot to mention that. I'm using the pip package.
```
$ pip show panel
Name: panel
Version: 0.5.1
Summary: A high level dashboarding library for python visualization libraries.
Home-page: http://pyviz.org
Author: PyViz developers
Author-email: developers@pyviz.org
License: BSD
Location: /usr/local/lib/python3.7/site-packages
Requires: pyviz-comms, testpath, pyct, markdown, bokeh, param
Required-by:
```

**Comment by philippjfr** [comment]
Panel 0.6.0 is now released and I've fixed the issues packaging the precompiled models so imports should be fast now.

**Comment by gioarma** [comment]
Sorry if I reopen this, but I'm having the same issue with Panel version _0.7.0a15_, installed with conda. In jupyter lab with the code:

```python
%%time

import panel as pn
pn.extension()
```
I get:
```
CPU times: user 1.01 s, sys: 208 ms, total: 1.22 s
Wall time: 18.1 s
```
Which is still very slow.
Sorry, I'm new to python and programming in general so I don't know if I missed something from this or other issues.

**Comment by philippjfr** [comment]
How did you install panel?

**Comment by philippjfr** [comment]
Sorry didn't read closely enough.

**Comment by philippjfr** [comment]
Could you run:

```
%%prun
import panel as pn
pn.extension()
```

and provide the output?

**Comment by gioarma** [comment]
I attach a txt file with the output
[prun.txt](https://github.com/holoviz/panel/files/4019530/prun.txt)

**Comment by philippjfr** [comment]
Ah, quick question, why do you have 0.7.0a15 and not just 0.7.0? Could you try installing the latter and try again?

**Comment by gioarma** [comment]
I installed it with:
` conda install -c conda-forge panel `
and when I run `conda list` I get:
`panel                     0.7.0a15                   py_0    pyviz/label/dev`.

If now I run `conda install panel=0.7.0` I get `All requested packages already installed.` Should I uninstall panel and run `conda install panel=0.7.0` again?

**Comment by philippjfr** [comment]
That's really bizarre, yes please try that.

**Comment by gioarma** [comment]
Ok, I uninstalled it and reinstalled it with `conda install -c conda-forge panel`. It installed the `0.6.4` version  and now I get 

```
CPU times: user 986 ms, sys: 242 ms, total: 1.23 s
Wall time: 1.42 s
```
Much better!

**Comment by philippjfr** [comment]
I'd recommend upgrading to 0.7.0 still.

**Comment by gioarma** [comment]
Ok, thank you very much!

**Comment by gioarma** [comment]
By running `conda update panel` I get: `All requested packages already installed.` and the version is still `0.6.4`, am I doing something wrong?

**Comment by philippjfr** [comment]
conda prefers not to update packages if another dependency also has to be updated, to force it specify the version explicitly with:

```
conda install panel=0.7.0
```

**Comment by gioarma** [comment]
Tried to run `conda install panel=0.7.0` but after more than 10 minutes loading I aborted becaused it seemed to be stuck. Here's the terminal output:
```
$ conda install panel=0.7.0
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: - failed
```

In the last line I interrupted with `Ctrl + C`

**Comment by philippjfr** [comment]
Okay, thanks, I guess I don't quite know what the conflict is. I'm guessing it's the fact that you have bokeh 1.1.0 and something else that depends on bokeh <1.3.0. Since Panel 0.7 requires bokeh>=1.3.0 it can't solve your environment which caused all this trouble.
