### ISSUE TITLE
Add height argument on param.ListSelector

### ISSUE THREAD

**Issue by henriqueribeiro** [pyviz/panel#456]
It would be good to be able to set the height of the param.ListSelector, like in the example below.

```python
class Example(param.Parameterized):

    test = param.ListSelector(default=['a'], objects=['a', 'b', 'c', 'd', 'e', 'f'], height=10)

    @param.depends("test")
    def view(self):
        return self.test

example = Example()
pn.Row(example.param, example.view)
```

**Comment by philippjfr** [comment]
Param is not a UI framework so this will never happen. What we can support is providing additional hints for the widget creation via the widgets keyword on the Param pane, so I can imagine something like this:

```python
pn.panel(example.param, widgets={'test': {'size': 10}})
```

**Comment by henriqueribeiro** [comment]
Hey @philippjfr, do you have any hint where I can start to implement this?
