### ISSUE TITLE
DatePicker display value doesnt get updated

### ISSUE THREAD

**Issue by rtmatx** [pyviz/panel#472]
Hi,

My issue is related to the image shown below

Even though the value of `date_picker` widget is changed, the value shown in display in the first cell is not updated. Whereas, for `select` widget the value is updated in the last two cells.

I did some digging around DatePicker and noticed that `_process_property_change` is implemented but not `_process_param_change`. Not sure, if this is relevant observation.

I also noticed that date shown is off by a day when it is exactly at mid-night. Wondering if this is implemented knowingly in this way or if it is due to `datetime` module.

I used the solution mentioned in #421  to update the `_process_property_change` as I am not able to make a selection otherwise

![image](https://user-images.githubusercontent.com/23462596/59056365-a5697a00-885d-11e9-8f9a-98274b0406d6.png)

**Comment by philippjfr** [comment]
Is this issue different from #421 in some way?

**Comment by rtmatx** [comment]
This issue is different from that. #421 addresses an issue where there used to be errors upon picking a date value. But this issue focuses on the display value not getting updated even when the underlying value got channged

**Comment by philippjfr** [comment]
Okay thanks! Stretched thin right now, so didn't have time to look in detail.

**Comment by rtmatx** [comment]
No problem @philippjfr. This is not a pressing issue. I used `DatetimeInput` widget which helped in what I am looking for in the input

I searched for bit more and realized that this issue is mentioned in bokeh https://github.com/bokeh/bokeh/issues/8934 . I will close this unless there is any need to address it here

**Comment by philippjfr** [comment]
Let's keep it open, that way I may remember to fix it upstream.

**Comment by philippjfr** [comment]
Appears to be fixed.
