### ISSUE TITLE
Graphs don't respond to widget changes

### ISSUE THREAD

**Issue by joseph-allen** [pyviz/panel#476]
I am on a macbook and the graphs never respond to any inputs from me, even on the [demo site](https://panel.pyviz.org/getting_started/index.html)

[Demo Gif](https://gyazo.com/a5ece6e70c1bd1b9b3a97aecd7483770)

**Comment by philippjfr** [comment]
There should definitely be a disclaimer there or we should enable embedding. The website consists of statically rendered notebooks, and without a Python server backing it most widgets will not be responsive by default. So while confusing this is actually expected, that said we should definitely find a better solution here.

The easiest thing to do would be to enable the embed option for certain notebooks.

**Comment by joseph-allen** [comment]
It also doesn't work inside my own notebooks, is there something I am supposed to enable for it to work?

This made me think it was a bigger problem than my setup.

**Comment by philippjfr** [comment]
>It also doesn't work inside my own notebooks, is there something I am supposed to enable for it to work?

Could you report your version of panel, param and which notebook environment you are using?

**Comment by joseph-allen** [comment]
panel: 0.5.1
param: 1.9.1

And im using jupyterlab

**Comment by philippjfr** [comment]
Have you installed the jupyterlab extension?

    jupyter labextension install @pyviz/jupyterlab_pyviz

I'd also recommend updating to panel 0.6.0.

**Comment by joseph-allen** [comment]
yes, I installed node and ran the above, restarted Jupyterlab and still no interactions.

**Comment by poplarShift** [comment]
So when you go 'Restart kernel and run all cells', all outputs are rendered but there is no interactivity?

**Comment by joseph-allen** [comment]
yep, same as in the gif above. I can drag the widget, it doesn't cause any re-rendering though

**Comment by jbednar** [comment]
Maybe quit your browser entirely and restart? Perhaps the newly installed stuff is not being used. If that doesn't help, what's on the JS console (under Developer Tools in Chrome)? Any messages suggesting a communications problem?

**Comment by joseph-allen** [comment]
have done, and no errors in the JS console.

**Comment by jbednar** [comment]
The gif above looks like it's from the website, where such behavior is expected, but you actually see the same behavior from a live Jupyter notebook, with no JS errors?  That seems very mysterious. :-(

**Comment by joseph-allen** [comment]
the behaviour was the same, it is working now, perhaps a full restart of my machine was needed, apologies everybody!
