### ISSUE TITLE
Changing the name of a param prevents updating widgets

### ISSUE THREAD

**Issue by hadim** [pyviz/panel#477]
Consider the following code:

```python
import panel as pn
import param


class TestViewer(param.Parameterized):
    
    time_param = param.Integer(default=0, bounds=(0, 10))
    
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        #self.param.time_param.name = "Time"
      
    @param.depends('time_param')
    def time_value(self):
        return f'Time Value {self.time_param}'
    
    def panel(self):
        param_widget = pn.panel(self.param)
        self.container = pn.Column(self.time_value)        
        return pn.Row(self.param, self.container)
      
viewer = TestViewer()
viewer.panel()
```

The slider will change the value of the string displayed in the `panel()`. Now if you uncomment the line `self.param.time_param.name = "Time"` in the `__init__` function then value displayed will stop being updated.

I think it's because the `name` attribute of the param needs to be the same as the one used in `@param.depends`.

Am I true? If I do then is that possible to decouple the name displayed on the widget to the name used in the Python code?

Best,

**Comment by jbednar** [comment]
Definitely don't change the `name`. I don't have time to test at the moment, but recent versions of Param should support changing the `label` (the displayed version of the name) instead, which should work as you intend.

**Comment by hadim** [comment]
Ok, I just realized reading #117 that I could use `self.param.time_param.label`.

Problem solved xD

**Comment by hadim** [comment]
Thank you @jbednar !
