### ISSUE TITLE
Default value on fn not respected by interact?

### ISSUE THREAD

**Issue by jbednar** [pyviz/panel#48]
```
import panel as pp
pp.extension()

def fn(a=1.7, b=1.7):
    return a,b

pp.interact(fn, a=(-2,2))
```

![image](https://user-images.githubusercontent.com/1695496/45783358-2e3a7a00-bc2b-11e8-806d-72f802f58a9d.png)

I had expected both a and b to initially be 1.7, but only b is.

**Comment by philippjfr** [comment]
Fixed in https://github.com/pyviz/panel/pull/49
