### ISSUE TITLE
Disabled for pn.WidgetBox

### ISSUE THREAD

**Issue by ahuang11** [pyviz/panel#502]
Would be nice to be able to set disabled=True on all the widgets inside a WidgetBox

`pn.WidgetBox.disabled = True`

**Comment by philippjfr** [comment]
Neat idea. Happy to accept a PR for that, basically you'd define something like:

```python
@param.depends('disabled', watch=True)
def _disable_widgets(self):
    for obj in self:
        if isinstance(obj, Widget):
            obj.disabled = self.disabled
```

additionally any methods that allow adding a new widget or replacing an existing one would have to toggle the disabled state.

**Comment by gwbischof** [comment]
Should all Layouts have a disabled property and not just WidgetBox?

**Comment by philippjfr** [comment]
>Should all Layouts have a disabled property and not just WidgetBox?

I'd prefer not to, WidgetBox is clearly meant for widgets an option that's a no-op for most contents of a Row/Column doesn't seem good to me.
