### ISSUE TITLE
DatePicker and Dateslider values should be a date

### ISSUE THREAD

**Issue by randomstuff** [pyviz/panel#507]
The `value` of ` DatePicker` and `Dateslider` should probably be a `date` instead of a `datetime` in order to follow the principle of least astonishment.

See #496.

This would be consistent with recent versions of [ipywidgets](https://github.com/jupyter-widgets/ipywidgets/issues/1393).

**Comment by randomstuff** [comment]
See as well the related [PR 348 for param](https://github.com/pyviz/param/pull/348).

**Comment by jsignell** [comment]
That seems very reasonable and doable.
