### ISSUE TITLE
Can RadioButtonGroup collapse and have navigator like Tabs?

### ISSUE THREAD

**Issue by ahuang11** [pyviz/panel#512]
```
options = list(map(str, range(0, 150)))
pn.widgets.RadioButtonGroup(options=options, width=200)
pn.Tabs(*options)
```

![image](https://user-images.githubusercontent.com/15331990/60917093-f09fef80-a244-11e9-9c1e-25741856c69a.png)

**Comment by philippjfr** [comment]
Seems like a good idea but that would be a feature request for bokeh, so I'll close.
