### ISSUE TITLE
Bokeh widgets extend outside of the space reserved for them

### ISSUE THREAD

**Issue by jbednar** [pyviz/panel#52]
As shown in https://github.com/pyviz/panel/pull/50 and https://github.com/pyviz/panel/issues/42, a Bokeh widget gets some space reserved for it by Panel, but it doesn't respect that space:

```
import param

class C(param.Parameterized):
    a = param.Number(1.7, bounds=(-2, 2))
    cmap = param.ObjectSelector(kbc,[kbc,fire])

    def view(self):
        return self.a, self.cmap[0]
c=C()
pp.Row(c.param,c.view)
```
![image](https://user-images.githubusercontent.com/1695496/45830726-570e4e00-bcc3-11e8-9a1e-af9b251eadfb.png)

Is there some flag we can pass to Bokeh that will make it truncate the representation ( before "(1.7," in this case), or else resize the box to fit it (not appropriate in this case, but appropriate for some of the cases in https://github.com/pyviz/panel/issues/42)?

**Comment by philippjfr** [comment]
This may be fixed by the layout refactor, so worth investigating at that point.

**Comment by philippjfr** [comment]
This is indeed fixed now.
