### ISSUE TITLE
interactivity not working on jupyterlab 1.0.2

### ISSUE THREAD

**Issue by afonit** [pyviz/panel#522]
I was trying out the new tutorial materials to follow the scipy demo video and ran into an issue.

Here is a short screencast:
![dragging_slider](https://user-images.githubusercontent.com/1798497/61149550-63ac9e80-a4af-11e9-90bf-49f772afe5a6.gif)

The slider is updating but the visual representation of the dataframe is not.

I created a new python environment:
```python
conda create -n data_analysis_lab python=3.7
conda activate data_analysis_lab
conda install -c conda-forge jupyterlab
conda install -c pyviz holoviz
```

I started the old jupyter notebook and the demo works as expected - just seem to be an issue with jupyterlab and panel.

Here is what it looks like in the jupyter notebook:
![dragging_slider_works](https://user-images.githubusercontent.com/1798497/61150538-abccc080-a4b1-11e9-97fb-cf29deb3f63e.gif)

**Comment by philippjfr** [comment]
Have you installed the jupyterlab extension?

```
conda install -c conda-forge jupyterlab
jupyter labextension install @pyviz/jupyterlab_pyviz
```

**Comment by afonit** [comment]
@philippjfr , that was it in the new environment with 1.0.2.  Interestingly I had that extension in the old environment but on jlab .35 where it was also not working - though a mute point since 1.0.2 is now released.  thank you.
