### ISSUE TITLE
AttributeError: module 'panel.pane' has no attribute 'Plotly' for Plotly example.

### ISSUE THREAD

**Issue by TomBerton** [pyviz/panel#524]
Encountered the above AttributeError when I ran the [Plotly example](https://panel.pyviz.org/reference/panes/Plotly.html#gallery-plotly) form the Gallery. 

panel==0.4.0
plotly==3.10.0

<img width="660" alt="Screen Shot 2019-07-12 at 6 14 22 PM" src="https://user-images.githubusercontent.com/9907572/61162967-e560f400-a4d0-11e9-827f-9a13432fd616.png">

**Comment by philippjfr** [comment]
Panel 0.4.0 is considerably out of date at this point. The current version is 0.6.0

**Comment by TomBerton** [comment]
Thanks. When I used `conda install -c pyviz panel` to install Panel yesterday. v. 0.4.0 was installed.  Today it installed 0.6.0.

**Comment by jbednar** [comment]
Whoa, that's odd.  Definitely no Panel releases recently. Sometimes Conda acts in mysterious ways.
