### ISSUE TITLE
[ENH] Output simple streamz 

### ISSUE THREAD

**Issue by martindurant** [pyviz/panel#533]
hvplot currently handles streamz dataframes.

Ordinary streamz streams display as self-updating text in a notebook, using jupyter repr hooks (see `streamz.Stream._ipython_display_`). It would be very nice to be able to display these things in a Panel and include them in layouts.

**Comment by philippjfr** [comment]
Now added Streamz pane which handles all streamz output.

**Comment by martindurant** [comment]
Wooop! I hope you demo this sometime.
