### ISSUE TITLE
FileInput Adding a status param

### ISSUE THREAD

**Issue by ahuang11** [pyviz/panel#535]
Is there a way to change what "No file chosen" says? It automatically updates after uploading a file, but how do I access that name?

![image](https://user-images.githubusercontent.com/15331990/61406553-ee671200-a890-11e9-9515-6506d9b07647.png)

**Comment by jbednar** [comment]
I can't find that text anywhere in Panel, Bokeh, or Param, so I suspect it comes from the browser?

**Comment by philippjfr** [comment]
This text is hard coded into your browser, so sadly the answer is no.

**Comment by ahuang11** [comment]
So there's no way of clearing the current file chosen?
![image](https://user-images.githubusercontent.com/15331990/61466737-49e7dd00-a92f-11e9-94b3-9de437969e92.png)

**Comment by philippjfr** [comment]
> So there's no way of clearing the current file chosen?

Correct.

>I guess replacing the object works.

We could also add a method that does this.
