### ISSUE TITLE
Dateslider value doesn't update

### ISSUE THREAD

**Issue by owen-synergy** [pyviz/panel#536]
The DateSlider widget value doesn't update in sync with the displayed value - it just stays at the initial value. I used the example code as is (other than formatting tweaks).

![DateSliderValue](https://user-images.githubusercontent.com/50761413/61435803-ecbe4c80-a96b-11e9-8dd8-32e9e04acbb5.png)

I tried the DateRangeSlider and IntSlider for comparison and their value property did update in sync with their displayed value no problem.

I'm using Windows Conda panel version 0.6.0 (from the conda-forge channel) - with jupyterlab 1.0.2

**Comment by philippjfr** [comment]
Fixed now that param supports datetime.date.
