### ISSUE TITLE
remarks on Gapminders demo

### ISSUE THREAD

**Issue by stonebig** [pyviz/panel#542]
apparently in gapminders demo https://gapminder.pyviz.demo.anaconda.com/app:
- we don't see the country name of each dot
- we don't have the zooming interactivity on Altair & Matplotlib,
- Matplotlib horizontal axes is to small.

Maybe it's technical constraint of a bokeh server ?

**Comment by philippjfr** [comment]
None of these are technical constraints no. A PR to fix these issues would be appreciated 😄

**Comment by maxibor** [comment]
Made a [PR](https://github.com/pyviz-demos/gapminder/pull/4) on the gapminder notebook repository to apply these suggestions.

**Comment by philippjfr** [comment]
Well interactivity on matplotlib is not currently possible. The other issues have now been addressed.
