### ISSUE TITLE
GridSpec objects attribute violates Panel interface contract

### ISSUE THREAD

**Issue by analog-cbarber** [pyviz/panel#546]
The `Panel` class provides an `objects` attribute that is expected to contain a list of child objects:

```python
class Panel(Reactive):
   ...
    objects = param.Parameter(default=[], doc="""
        The list of child objects that make up the layout.""")
```

but `GridSpec` overrides this with a dictionary:

```python
class GridSpec(Panel):
   ...
    objects = param.Dict(default={}, doc="""
        The dictionary of child objects that make up the grid.""")
```

Consequently any code that is meant to operate on a `Panel .object` list is likely to break when applied to a `GridSpec`. In particular, the `Panel._cleanup`, which is inherited by `GridSpec` will fail because iterating over the objects will return tuples instead of the actual child objects.

For this case, you could probably fix this by overriding `_cleanup` in `GridSpec` but it would not fix the underlying issue.

Observed using Panel 0.6.0.

**Comment by philippjfr** [comment]
Thanks, most of the code in ``Panel`` should probably just move to ``ListPanel``.

**Comment by analog-cbarber** [comment]
Seems like this is might not be a `good first issue` if it involves a significant API change.
