### ISSUE TITLE
Runaway feedback loop when displaying multiple views of a vtk pane

### ISSUE THREAD

**Issue by jonmmease** [pyviz/panel#550]
#### Description of expected behavior and the observed behavior

When a VTK pane is displayed multiple times in a notebook, rotating one of the views often results in some sort of unstable feedback loop.  I've been trying to debug a similar issue (or at least apparently a similar issue) in https://github.com/pyviz/panel/pull/549 for the plotly pane.

#### ALL software version info (Panel, bokeh, python, notebook, OS, browser, any other relevant packages)

python 3.7
bokeh 1.3.0
panel 0.6.0
notebook 6.0.0

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import panel as pn
pn.extension('vtk')

dragon = pn.pane.VTK('https://raw.githubusercontent.com/Kitware/vtk-js/master/Data/StanfordDragon.vtkjs',
                     sizing_mode='stretch_width', height=400)
dragon
```
[first view]

```python
dragon
```
[second view]

![vtk_feeback3](https://user-images.githubusercontent.com/15064365/61995708-e1e57500-b059-11e9-8e4b-a85f93e1cba0.gif)

After rotating one of the views for a few seconds (sometimes is takes longer), the other view starts jittering and the notebook's process indicator shows that the there is continued feedback from the JavaScript side to the Python side.  The only way to break out of this state is to restart the kernel.

The VTK pane has logic already that seems like it should help prevent this kind of thing (See usage of the `_setting` property in `panel/models/vtk.ts`).  And after debugging this kind of issue in the Plotly pane in https://github.com/pyviz/panel/pull/549, I've been unable to pinpoint the source of the feedback.  So I'm wondering if there is something going on in a layer below the pane itself.

And here is the JavaScript console error the appears at the same time that the feedback loop starts:

Chrome:
![Screen Shot 2019-07-27 at 11 19 46 AM](https://user-images.githubusercontent.com/15064365/61996264-81a60180-b060-11e9-8f27-abfd5a93b8d7.png)

Interestingly, the console error looks very different in Firefox (same behavior though)
![Screen Shot 2019-07-27 at 11 22 09 AM](https://user-images.githubusercontent.com/15064365/61996298-de092100-b060-11e9-8d68-0f86fc751510.png)

**Comment by jonmmease** [comment]
Here are the results of another experiment.  This time I placed two references to the dragon pane in a `Column` layout.

```python
import panel as pn
pn.extension('vtk')

dragon = pn.pane.VTK('https://raw.githubusercontent.com/Kitware/vtk-js/master/Data/StanfordDragon.vtkjs',
                     sizing_mode='stretch_width', height=400)
pn.layout.Column(dragon, dragon).servable()
```
In the notebook I get the same error as above (Cannot read property 'content' of null), but I don't see the runaway feedback behavior.  After the error is raised the first time, the two views are no longer linked.

Here's what I see when I serve this notebook with `panel serve`:

![panel_serve_dragons](https://user-images.githubusercontent.com/15064365/61999902-496ee500-b099-11e9-92e2-293b6ddc52fd.gif)

When I drag the top view, everything is synchronized perfectly, with no runaway feedback state.  But when I drag the bottom view, the top view does not respond.

**Comment by philippjfr** [comment]
I think this is an issue with updates arriving from python triggering a JS change event which then bounces back to python. I thought this was fixed a while ago but I recently saw an indication that this can still happen in certain scenarios so I'll have to investigate.

**Comment by jonmmease** [comment]
I think I found the issue 🤞 PR forthcoming ...

**Comment by jonmmease** [comment]
PR https://github.com/pyviz/panel/pull/553
