### ISSUE TITLE
DatePicker value type error in notebook context

### ISSUE THREAD

**Issue by randomstuff** [pyviz/panel#556]
#### ALL software version info (Panel, bokeh, python, notebook, OS, browser, any other relevant packages)

* Debian testing
* Python 3.7.4
* `pip install panel`

<pre>
bokeh           1.3.0  
Jinja2          2.10.1 
Markdown        3.1.1  
MarkupSafe      1.1.1  
numpy           1.17.0 
packaging       19.0   
panel           0.6.0  
param           1.9.1  
Pillow          6.1.0  
pip             18.1   
pkg-resources   0.0.0  
pyct            0.4.6  
pyparsing       2.4.1.1
python-dateutil 2.8.0  
pyviz-comms     0.7.2  
PyYAML          5.1.1  
setuptools      40.8.0 
six             1.12.0 
tornado         6.0.3 
</pre>

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import datetime
import panel as pn
import panel.widgets as pnw
import panel.widgets.slider

a = datetime.date(2019, 1, 1)
b = datetime.date(2019, 12, 31)

pn.extension()
pnw.DateSlider(name="x", start=a, end=b, value=b)
```

#### Stack traceback and/or browser JavaScript console output

<pre>
Python failed with the following traceback: 
/home/gcorona/src/panel/panel/viewable.py _change_event L653
/home/gcorona/temp/test-toto/venv/lib/python3.7/site-packages/param/parameterized.py inner L1219
/home/gcorona/temp/test-toto/venv/lib/python3.7/site-packages/param/parameterized.py set_param L2572
/home/gcorona/temp/test-toto/venv/lib/python3.7/site-packages/param/parameterized.py set_param L1358
/home/gcorona/temp/test-toto/venv/lib/python3.7/site-packages/param/parameterized.py _f L294
/home/gcorona/temp/test-toto/venv/lib/python3.7/site-packages/param/parameterized.py _f L296
/home/gcorona/temp/test-toto/venv/lib/python3.7/site-packages/param/__init__.py __set__ L617
/home/gcorona/temp/test-toto/venv/lib/python3.7/site-packages/param/parameterized.py _f L296
/home/gcorona/temp/test-toto/venv/lib/python3.7/site-packages/param/parameterized.py __set__ L823
/home/gcorona/temp/test-toto/venv/lib/python3.7/site-packages/param/__init__.py _validate L1830
	ValueError: Date 'value' only takes datetime types. auto-k line 103453 > scriptElement line 137 > Function:65:13
</pre>

**Comment by jbednar** [comment]
Thanks for the well-written bug report and the PR!!!!!!
