### ISSUE TITLE
Param classes defined in external file and inheritance

### ISSUE THREAD

**Issue by kcpevey** [pyviz/panel#56]
I have a use case for panel that's difficult to describe without a demo so I'm attaching two files. The notebook walks through my issue.   
  
[user_guide.zip](https://github.com/pyviz/panel/files/2405684/user_guide.zip)  
  
I'd be interested to hear any thoughts on how I can improve this approach.

**Comment by philippjfr** [comment]
The issues seem to be fixed according to my testing, if you can confirm could you close this?

**Comment by kcpevey** [comment]
I updated param and panel to master and now I can't get the panel to display. I'm getting a javascript error:  
  
![panel](https://user-images.githubusercontent.com/15659110/46367173-89fcfe00-c642-11e8-847f-87d2b4f97d33.PNG)

**Comment by philippjfr** [comment]
Could you report the versions you've got for each? I can't reproduce that.

**Comment by philippjfr** [comment]
JupyterLab and jupyterlab_pyviz versions may also be useful.

**Comment by kcpevey** [comment]
param                     1.8.0a8.post5+ga97c18b      
panel                     0.1.0a11.post3+ge8e0f6d.dirty   
jupyter                   1.0.0                     
jupyter_client            5.2.3                 
jupyter_console           5.2.0             
jupyter_core              4.4.0                  
jupyterlab                0.34.6                
jupyterlab_launcher       0.13.1   
@pyviz/jupyterlab_pyviz v0.6.1

**Comment by philippjfr** [comment]
Thank you!

**Comment by philippjfr** [comment]
Okay updated JupyterLab and can now reproduce the issue. I'll try to get an updated `jupyterlab_pyviz` release out with a fix.

**Comment by philippjfr** [comment]
Okay nevermind, it's not an issue with the extension, it's merely down to the fact that you haven't loaded the extension. So try clearing the output, and then loading the panel (or holoviews) extension:

```
panel.extension()
```

**Comment by kcpevey** [comment]
Not sure how I was missing that before when this was working. At any rate, `panel.extension()` doesn't seem to fix it for me.  
  
![panel2](https://user-images.githubusercontent.com/15659110/46370909-87070b00-c64c-11e8-924b-5a5472c7d28c.PNG)
  
I'm heading out for the day, I'll pick back up with this tomorrow.

**Comment by philippjfr** [comment]
I had to clear the notebook and reload the page for some reason.

**Comment by kcpevey** [comment]
Got it working. My guess is that the other tab was hanging on to a previous build.  
  
Now, is this expected behavior given how I have this coded?:  
![solve_on](https://user-images.githubusercontent.com/15659110/46415116-3645ef80-c6ea-11e8-854d-127b59852dda.PNG)

**Comment by kcpevey** [comment]
And can you confirm that this:  
  
```
loc = foo.location(name='')    
adv = foo.advanced(name='')  
Tabs(('INPUT', loc), ('Advanced', adv))  
  
foo.launch(loc.solve_on, adv.notebook)    
```
  
Is the cleanest and most efficient way to apply my code?

**Comment by philippjfr** [comment]
>Now, is this expected behavior given how I have this coded?:

No, appears to be a bug, I can see an error on the console.

**Comment by philippjfr** [comment]
Fixed in https://github.com/ioam/param/pull/289

**Comment by kcpevey** [comment]
What I was hoping for (and what I *think* worked in a previous iteration of my code without panel and possibly with a different class setup) was this:  
  
```
Tabs(('INPUT', foo.location), ('Advanced', foo.advanced ))  

foo.launch(foo.location, foo.advanced) 
```  
  
And something like this:   
```
def launch(location, advanced):  
   v = solve_on  
   g = notebook  
```  
  
Where basically because `launch` was inheriting `param.Parameterized` classes and I could just use the objects from those classes directly inside the method (e.g. solve_on above). It felt weird at first because its not clear what's going on, but I eventually liked it because it made my code so clean. Is this not possible now with the way I have it set up above?  
  
If this isn't clear, I can demo what I have on a call next week.

**Comment by kcpevey** [comment]
Orrrr.... could I write a subfunction in each `param.Parameterized` class that simply returned all the objects. Then I could call launch like this:  
  
`foo.launch(foo.location.return_objs(), foo.advanced.return_objs()) `  
  
And then I'd just have to unpack the input.   
  
And for reference... this is what I currently have based on your last suggestion, which is a nightmare:   
```
solve_obj = solve2.solve(loc_param.solve_on, loc_param.solve_from, loc_param.local_architecture, 
                         login_param.hpc_login_node, submit_param.hpc_subproject, submit_param.workdir,
                         submit_param.nodes, submit_param.wall_time, submit_param.queue, 
                         submit_param.submit_script_filename, adv_param.notebook, input_param.sim_files, 
                         input_param.model, input_param.adh_rootname, input_param.adh_root_filename, 
                         input_param.adh_directory)
```

**Comment by philippjfr** [comment]
Could you describe what exactly about this isn't working? I can't reproduce any problem with what you're describing. I don't quite follow the difference between ``foo.launch`` and the ``launch`` function. The other thing I don't follow is this:

```python
foo.launch(foo.location, foo.advanced) 
```

There is no reason to pass those parameters to the ``launch`` method since they are available on self. I *think* what you really want is a classmethod?!

```python
class location(param.Parameterized):
    solve_on = param.ObjectSelector(default='topaz', objects=['topaz', 'desktop'], precedence=1)
    
class advanced(param.Parameterized):
    notebook = param.Boolean(default=True, precedence=9)
    
class solve(location, advanced):
    @classmethod
    def launch(cls):
        if cls.solve_on == 'desktop':
            print('bar')
        if cls.notebook:
            print('notebook')
```            

If this isn't what you want let's discuss next week.

**Comment by kcpevey** [comment]
OoOoOo I didn't know that I was a thing (engineer != programmer). That seems like it might be what I'm looking for. Let me work on this a bit and get back with you.

**Comment by kcpevey** [comment]
And to answer your question. Its all working, its just much less clean than it was before I implemented Panel so I want to make sure that I'm streamlining things as much as possible.

**Comment by philippjfr** [comment]
So param actually also provides a ``bothmethod`` decorator, which means you can use the method on the class or an instance of the class which may also be useful:

```python
class solve(location, advanced):
    @param.parameterized.bothmethod
    def launch(self_or_cls):
        if self_or_cls.solve_on == 'desktop':
            print('bar')
        if self_or_cls.notebook:
            print('notebook')
```

**Comment by kcpevey** [comment]
@philippjfr Have you had a chance to look at the solve code I sent yet? I have a soft deadline for a demo at the end of the week and I'd love to use the more streamlined version of that code.

**Comment by philippjfr** [comment]
Looking at this now, hope to get back to you very soon.

**Comment by kcpevey** [comment]
works great! thanks!!
