### ISSUE TITLE
Disable pan tool on pipeline subway map

### ISSUE THREAD

**Issue by ahuang11** [pyviz/panel#563]
In https://panel.pyviz.org/user_guide/Pipelines.html, you can drag the pipeline object around.

Would it be possible to also drag and resize gridspecs (make the top pane larger and bottom pane smaller by dragging the center point, like how you can move/resize windows in an OS).

```
import panel as pn
pn.extension()

gs = pn.GridSpec()
gs[0:25, 0:50] = pn.Spacer(background='Red')
gs[25:50, 0:50] = pn.Spacer(background='Blue')
gs
```

![image](https://user-images.githubusercontent.com/15331990/62157439-ccc74b00-b2d2-11e9-8dc8-ebb5de952c9d.png)

**Comment by philippjfr** [comment]
Almost certainly not, the only reason you can drag the pipeline around is that it's a plot and I forgot to disable the pan tool on that plot. The ability to resize plots is a rather large feature request for bokeh. I've repurposed the issue.

**Comment by jbednar** [comment]
I still see this issue on latest Panel and HoloViews master as of today, with the latest Bokeh dev release.
