### ISSUE TITLE
Replace tabs.objects yields different results from initializing tabs

### ISSUE THREAD

**Issue by ahuang11** [pyviz/panel#578]
```
import panel as pn
pn.extension()

items = [('a', 1), ('b', 2)]
tabs1 = pn.Tabs(*items)
tabs1

items2 = [('c', 3), ('d', 4)]
tabs2 = pn.Tabs(*items2)
tabs2

tabs1.objects = items2
```

Not sure if this is a bug since `objects` are consistent with other widgets (objects => content).

However, I would like maybe a separate method that lets me replace the content and names so that `tabs1 == tabs2`

Currently, setting `tabs1.objects` inserts tuples

![image](https://user-images.githubusercontent.com/15331990/62667643-2fad8780-b94e-11e9-85b5-1f80904d4f89.png)

**Comment by philippjfr** [comment]
This will do it:

```python
tabs1[:] = items2
```
