### ISSUE TITLE
`step` doesn't do anything on Player

### ISSUE THREAD

**Issue by ahuang11** [pyviz/panel#591]
```
import panel as pn
pn.extension()
plyr = pn.widgets.Player(start=0, end=100, step=10)
```
expect 10 increments, but found a lot

**Comment by a-recknagel** [comment]
@ahuang11 I can't reproduce the bug. If I use your setup it seems to use the steps correctly as far as I can see. Can you send an actual test case that I can run and shows the complete behavior? Until then I'll close this issue.
