### ISSUE TITLE
Support reading from BytesIO/StringIO

### ISSUE THREAD

**Issue by ahuang11** [pyviz/panel#610]
I'm trying to write a GIF to memory and use panel to read from memory rather than storage.
`ValueError: GIF pane does not support objects of type 'BytesIO'`

```
from io import BytesIO
import imageio

memory = BytesIO()

save_fps = [..]

with imageio.get_writer(memory, mode='I', format='gif', fps=8) as writer:
    for fp in save_fps:
        image = imageio.imread(fp)
        writer.append_data(image)

memory.seek(0)
pn.pane.GIF(memory)
```

**Comment by jbednar** [comment]
Extending it to support a file-like object should be reasonable; sure.  I think you'd need to add a case for that in panel.pane.image.ImageBase:_img(); it currently accepts a string that it interprets as a file path or as a URL.
