### ISSUE TITLE
Panel table widget similar to holoviews table widget

### ISSUE THREAD

**Issue by ericdill** [pyviz/panel#619]
**Is your feature request related to a problem? Please describe.**
It's not immediately obvious how to present some / all of the contents of a pandas dataframe to the user in a panel dashboard.

**Describe the solution you'd like**
The holoviews Table widget has two pretty awesome features that make it interesting to use in a panel dashboard that the panel table widget is missing:
1. sortable columns
2. scroll bar and defined widget size

**Describe alternatives you've considered**
I am not sure how to answer this question

**Comment by philippjfr** [comment]
PR #560 adds a widget like this. I'd like to handle (multi)-indexes properly in that pr which would make it more powerful than even the HoloViews table. But I want that to be in the next release (0.7.0).

**Comment by philippjfr** [comment]
The DataFrame widget is now merged.
