### ISSUE TITLE
BUG: pip install panel version doesn't import

### ISSUE THREAD

**Issue by linwoodc3** [pyviz/panel#62]
I'm running through the **Scipy 2018 PyViz** tutorial and *command 16* on the `01_Workflow_Introduction` notebook uses `panel`.

When I use a `pip install` version of `panel`, I get:

```python
import panel
[Out]:ModuleNotFoundError: No module named 'panel'
```
The `pip install` version is `panel-0.0.1` and I confirmed that it was installed in my environment with `conda list` and `pip freeze`.
![panel](https://user-images.githubusercontent.com/2884914/45923238-787f5d80-beae-11e8-90cd-439d6412ddca.png)

However, when I install with conda using `conda install panel -c pyviz`, the import works with no issues.  

![panel_conda](https://user-images.githubusercontent.com/2884914/45923244-b9777200-beae-11e8-9345-1e12cbcee005.png)

**Comment by philippjfr** [comment]
Thanks for the report, we haven't yet released an official version of panel and uploaded a package to PyPI solely to register the name. We are getting very close to a first release though, so I'll keep you updated.

**Comment by philippjfr** [comment]
To get the current dev releases:

```
conda install -c pyviz/label/dev param panel
```

**Comment by linwoodc3** [comment]
That worked.
