### ISSUE TITLE
[DOC] /user_guides/Panes.html is missing

### ISSUE THREAD

**Issue by rs2** [pyviz/panel#628]
#### ALL software version info:
Whatever was used to generate https://panel.pyviz.org/.

#### Description of expected behavior and the observed behavior
No hyperlinks in https://github.com/pyviz/panel/blob/master/examples/user_guide/Param.ipynb yield a 404.

#### Complete, minimal, self-contained example code that reproduces the issue
https://panel.pyviz.org/user_guide/Panes.html is not available, and I could not find suitable candidates in https://github.com/pyviz/panel/tree/master/examples/user_guide. See https://github.com/pyviz/panel/pull/466/files#diff-ce01fb962ef569b34c1649450526e27cR238. for the diff that introduced it.

**Comment by jbednar** [comment]
I found a copy of Panes.ipynb on my hard drive, but I think it was just a sketch that wasn't really part of the proper documentation.  It's hard to remember now, but it looks like we decided not to have an overview of panes other than in Components.ipynb, and instead just exhaustively list all of them in the Reference Gallery.  So we should probably just change this link to point to the Panes section of Components.ipynb, or to the Panes section of the Reference Gallery.

**Comment by a-recknagel** [comment]
I can't find references to a Panes.html anywhere in the project, can you @rs2 give a better description on where this link would be found, full url to the containing page and a screenshot of the rendered link?

**Comment by rs2** [comment]
@a-recknagel Search for `Pane objects` in https://panel.pyviz.org/user_guide/Param.html.
Xref: https://github.com/pyviz/panel/pull/466/files#diff-ce01fb962ef569b34c1649450526e27cR238.

**Comment by a-recknagel** [comment]
Thanks, found it. In lieu of an option to link to sections of `.ipynb` files I'll just link to `Components` instead. Better than 404.

**Comment by jbednar** [comment]
You can link to sections of .ipynb files; just do "file.ipynb#Section-name", for a section named "Section name".

**Comment by a-recknagel** [comment]
I can't fully test it localy, when I build the docs the `.ipynb` part of the urls don't get turned into `.html`, but obviously that's what happens in the actual deployment. So I guess I can start the PR. In case anyone knows, do I need to do something else besides this?

```bash
$ nbsite generate-rst --org pyviz --project-name panel
$ sphinx-build doc public -b html -a
```
