### ISSUE TITLE
Port not being released after stopping threaded holoviz panel app server

### ISSUE THREAD

**Issue by friedrichknuth** [pyviz/panel#634]
Closing a threaded panel app holds on to the port it started on. This is different behavior than closing an app initialized without threading.

```
usgs_logo = pn.panel('../assets/usgs_logo.png', height=130)

column = pn.Column(usgs_logo)

app = column.show(port=8889)

app.stop()
```

Port 8889 is released.

```
app = row.show(port=8889, threaded=True)

app.stop()
```
Port 8889 is not released.

**Comment by jsignell** [comment]
I am moving the issue over to panel for tracking, but I don't have any immediate insight. Thanks for raising it though.
