### ISSUE TITLE
FileInput: option to not upload file contents

### ISSUE THREAD

**Issue by dmnfarrell** [pyviz/panel#640]
As I understand it the widget attempts to always load the file contents and store this in the value attribute. I would like to be able to use the file browser to select the names of very large files without loading the data as it is not required and currently hangs the notebook. Would it be possible to have an option to ignore file contents?

**Comment by jbednar** [comment]
param.Filename?

**Comment by philippjfr** [comment]
>Would it be possible to have an option to ignore file contents?

Should be possible but I have some doubts about how useful this is. You will only ever get the filename, never the full path to a file.

**Comment by dmnfarrell** [comment]
Ok so the full path can never be returned by the browser? I thought it might be possible when reading this thread: https://github.com/pyviz/panel/issues/430

**Comment by philippjfr** [comment]
No, the browser's don't allow it for security reasons. I think what you are after is the FileBrowser feature described in that issue which will allow browsing files on the server rather than the client and which will allow returning a full file name.

**Comment by philippjfr** [comment]
Will close this because I don't think a widget that returns only the filename is meaningful and I believe a server side FileBrowser is what you're really after.
