### ISSUE TITLE
pn.pane.HTML('holomap.html')

### ISSUE THREAD

**Issue by ahuang11** [pyviz/panel#652]
I know there's pn.pane.HoloViews, but I thought this would work too.
```
import panel as pn
pn.extension()

import xarray as xr
import holoviews as hv
hv.extension('bokeh')

ds = xr.tutorial.open_dataset('air_temperature').isel(time=slice(0, 15))

overlay = hv.Dataset(ds).to.image(['lon', 'lat'])
hv.save(overlay, 'test.html')

pn.pane.HTML('test.html').embed()
```

**Comment by philippjfr** [comment]
There's no point calling embed on an html since embed only does anything if there are widgets. Also this works:

```python
pn.pane.HTML(open('test.html').read(), height=500)
```

**Comment by philippjfr** [comment]
To be clear I do not think HTML should load external files, it makes sense for images but you might genuinely want to render 'test.html' or some other filename in an HTML pane.

**Comment by ahuang11** [comment]
Although this `pn.pane.HTML(open('test.html').read(), height=500)` shows the image, the slider is unresponsive. Is there a way to piece together several holomaps exported as HTML (without reprocessing the data)?
