### ISSUE TITLE
Improve flexibility of Pipeline workflows

### ISSUE THREAD

**Issue by philippjfr** [pyviz/panel#656]
The `Pipeline` class was introduced early on as an easy way to connect multiple stages of a pipeline. The initial version was deliberately very simple allowing for chaining a linear progression of stages, which covers a wide range of workflows. However for more complex workflows a simple linear progression is not sufficient, therefore we should find a way to allow expressing arbitrary directed acyclic graphs (DAGs) in a pipeline, specifically we want to support both branching and converging graphs using pipelines.

## The datastructure

The main issue to get this working is how we should represent the graph datastructure. The most standard representation of a DAG is an adjacency list, which in Python is most naturally expressed as a dictionary mapping from an input node to the output nodes. This differs significantly from the current implementation which is simply a linear list of stages. While we could theoretically represent branching pipelines by nesting multiple pipelines within each other, this would not allow expressing converging branches at a later stage.

Thankfully we can easily extend the existing API with an adjacency list. Currently the stages must be added by giving them both a name and the actual stage object. If supplying just this list we just continue assume that the graph is a linear chain, however if an adjacency mapping is supplied mapping name to names then the graph is computed from this mapping.

## The API

As a simple example here is what declaring a simple branching and converging graph could look like using the adjacency list approach:

```python
pipeline = Pipeline()
pipeline.add_stage('Values', EnterValues)
pipeline.add_stage('Add', Add)
pipeline.add_stage('Multiply', Multiply)
pipeline.add_stage('Display', Display)
pipeline.add_graph({'Values': ('Add', 'Multiply'), 'Add': ('Display',), 'Multiply': ('Display')})
```

```
                |--  Add   ---|
Enter Values ---|             |----Display
                |--Multiply---|
```

## The UI

In order to support branching pipelines there needs to be some way to choose between the different edges in the graph so we have to work out nice UI. One solution is to replace the "Next" button with a number of buttons for each of the branches. This could clutter up the page when you're trying to display the contents of the stage itself, so alternatively we could also insert a page between the stages where you choose the stage you want.

Alternative proposals for the data structure, API and UI welcome.

Cc: @jlstevens @jbednar @sdc50

Supersedes https://github.com/pyviz/panel/issues/419

**Comment by jbednar** [comment]
Sounds good!  Some non-binding thoughts:

- If we can show the DAG the same way we currently show the pipeline (i.e. like a graphviz/dot diagram), I think we could indicate the current and default Next stage graphically. Then Next would go to the default stage, while a non-default option could be selected by clicking on that node in the displayed graph.   
- For a large graph with many options this may not work, in which case we could maybe support a selector for choosing the next value, with the rest of the displayed pipeline matching whatever the currently selected value leads to with its default later choices.  I can draw an example of this if the idea isn't clear...

**Comment by philippjfr** [comment]
>If we can show the DAG the same way we currently show the pipeline (i.e. like a graphviz/dot diagram), I think we could indicate the current and default Next stage graphically.

I think the concept of a default stage makes sense in certain circumstances but might be confusing in other cases.

**Comment by jbednar** [comment]
> I think the concept of a default stage makes sense in certain circumstances but might be confusing in other cases.

For those cases presumably the Next and Previous buttons can be eliminated with an option?
