### ISSUE TITLE
Cursor keys in notebooks

### ISSUE THREAD

**Issue by jbednar** [pyviz/panel#66]
In Chrome, clicking on a Panel slider widget will turn the outline blue, and then the slider can be controlled by the left and right arrow keys:
![image](https://user-images.githubusercontent.com/1695496/46291902-411b4b80-c555-11e8-914c-2194636e83aa.png)
This is very convenient, but the cursor keys are also used to scroll horizontally in a Jupyter notebook output cell, whenever the output is larger than the area of that cell. In that case, the output scrolls whenever the widget is adjusted using the arrow keys, which is very confusing and distracting.  Is there some way for the widget to swallow the keypress events once it uses them so that they aren't also available to Jupyter to control the horizontal scrolling of the output area?  If one does want to scroll that area, one can simply not have a widget highlighted, and it seems like once the widget is highlighted only that widget should be processing the keypress events.

**Comment by philippjfr** [comment]
>Is there some way for the widget to swallow the keypress events once it uses them so that they aren't also available to Jupyter to control the horizontal scrolling of the output area?

No, this is a general issue with all kinds of interactions in the notebook and should be opened as an issue on the bokeh issue tracker. I suspect it's a very hard problem though. I'll close as this is definitely  not something we can address in panel.
