### ISSUE TITLE
Divider line for widgets

### ISSUE THREAD

**Issue by ahuang11** [pyviz/panel#663]
In markdown, if you type ---, it creates a divider line. I was thinking maybe panel should have something similar: pn.layouts.divider()?

![image](https://user-images.githubusercontent.com/15331990/65619364-a39b0200-df85-11e9-9646-16fe1a44cec8.png)

**Comment by philippjfr** [comment]
No objection but it's worth noting that you can already do this:

![Screen Shot 2019-09-25 at 9 11 16 PM](https://user-images.githubusercontent.com/1550771/65632046-0ec1f400-dfd9-11e9-9705-6e53580465d7.png)

**Comment by ahuang11** [comment]
Very cool!
