### ISSUE TITLE
panel dependency markdown compatibility problem

### ISSUE THREAD

**Issue by ea42gh** [pyviz/panel#669]
installing the latest version Markdown-3.1.1
results in a `No module named 'fenced_code'`
error for a panel markdown pane.

**Comment by jbednar** [comment]
But is ok for 3.0?

**Comment by philippjfr** [comment]
Yes, 3.0.1 is fine.

**Comment by philippjfr** [comment]
This needs more investigation, it's not quite clear what's causing the issue but it may be related to the plugins we enable.

**Comment by Karamya** [comment]
Cannot reproduce the issue with markdown version 3.1.1

<img width="565" alt="Screenshot 2019-10-13 at 15 58 44" src="https://user-images.githubusercontent.com/19229613/66716887-51563f80-edd3-11e9-94d7-6cd34b161d0a.png">
