### ISSUE TITLE
depends(obj.param) should not require obj to be expanded

### ISSUE THREAD

**Issue by jbednar** [pyviz/panel#67]
Right now for the Param pane, if a Parameterized declares a wached dependency on a subobject's .param, the callback is triggered only if the subobject is expanded in the panel. E.g. for:

```
class A(param.Parameterized):
    p = param.ObjectSelector(P())

    @param.depends("p.param", watch=True)
    def fn(self):
        pass
```

if one expands `p` by pressing `...` and edits some parameter of `p`, then  `fn()` is called, but `fn()` is (erroneously) not called if `p` is not expanded and someone separately does something like `p.a=2`.  Given that the dependency is declared independently of any GUI, I think `fn()` should be called *whenever* `p`'s parameters change, whether or not the item is expanded in a GUI.

**Comment by philippjfr** [comment]
I think this was always a param issue unless I'm mistaken. If so could you close?

**Comment by jbednar** [comment]
I'm not sure how it could be a param issue if it has to do with the state of Panel, but in any case I was not able to replicate the problem just now:

```
import param, panel as pn
pn.extension()

class A(param.Parameterized):
    a = param.Number(7, bounds=(0,10))
    b = param.Boolean(True)
    c = param.String("Yes")

class B(param.Parameterized):
    p = param.ObjectSelector(A())

    @param.depends("p.param", watch=True)
    def fn(self):
        print("fn")
        pass
    
b=B()
pn.Row(b)
```

Here if I do `b.p.a=x`, where `x` is some value other than the current value of `p.a`, then `fn` is printed whether or not the object is expanded.

**Comment by philippjfr** [comment]
>I'm not sure how it could be a param issue if it has to do with the state of Panel

I don't think it has anything to do with panel anymore. You mentioned at some point that it was making a new instance of the object for whatever reason which I think was the real cause of this.

**Comment by jbednar** [comment]
I don't *think* that was a related issue; the new instance that was unintentionally being created was on instantiation of the class B, regardless of the state of expansion of the widget B.p.  So if my description above is accurate, then whatever problem there was would have had to be related to the subobject expansion code in Panel.  In any case, I might have been confused about that earlier, and moreover the subobject code has now changed dramatically, so I'm not surprised that the problem has gone away.  We'll file a new issue if we see it again someday!

**Comment by philippjfr** [comment]
I too was confused earlier and wrongly claimed the issue might be related to the expansion code, which I now realize is not possible, but as you say no reason to worry about it if it appears fixed.
