### ISSUE TITLE
Holomap objects saved to html via panel show wrong widgets

### ISSUE THREAD

**Issue by Jacob-Barhak** [pyviz/panel#672]
This problem is reported in panel, yet may relate to another problem in holoviews reported here: https://github.com/pyviz/holoviews/issues/3849

When creating a holoviews holomap and saving them via panel, the holomap widgets do not list proper list of options and they are non functional. 

I am using Python 3.7.4 , panel 0.5.1, holoviews 1.12.3

Here is the code to reproduce the problem:
```
import holoviews as hv
import panel as pn

import numpy as np

hv.extension('bokeh') 

frequencies = [0.5, 0.75, 1.0, 1.25]


def sine_curve(phase, freq):
    xvals = [0.1* i for i in range(100)]
    return hv.Curve((xvals, [np.sin(phase+freq*x) for x in xvals]))

phases      = [0, np.pi/2, np.pi, 3*np.pi/2]

curve_dict_2D = {(str(p),str(f)):sine_curve(p,f) for p in phases for f in frequencies}
hmap = hv.HoloMap(curve_dict_2D, kdims=['phase', 'frequency'])

p = pn.panel(hmap)
p.save('test.html')
```
Here is an image showing the phase listbox contents that should have had only 4 values - it has 12

![image](https://user-images.githubusercontent.com/1986155/66082584-0d8c4c00-e530-11e9-9a91-63c6d90c8f7c.png)

So it seems that panel duplicates values without need - note that selecting a value does not change the image - so the problem is not only in display. 

Hopefully reporting this under panel is OK.

**Comment by philippjfr** [comment]
Two things, please only file issues that exist on master. Secondly panel 0.6.0 is quite outdated. Also to save the state you need to set ``embed=True``:

```python
p.save('test.html', embed=True)
```

**Comment by philippjfr** [comment]
To be clear, we don't actually expect people to actually check out master, but at minimum you should test the latest released version.

**Comment by Jacob-Barhak** [comment]
Verified as fixed on:

holoviews version 1.13.0a21.post10+gdf1a5803
panel version 0.8.0a2
bokeh version 1.4.0
