### ISSUE TITLE
Add subpanel expansion options

### ISSUE THREAD

**Issue by jbednar** [pyviz/panel#69]
Right now, when a Parameterized object with a Parameter `obj` that is also a Parameterized is displayed in a Param pane, Panel will create an extra widget `...` that when clicked will open a separate set of widgets to edit that subobject's parameters.  This is useful behavior for property sheets, which need to handle any arbitrary collections of nested objects, but when designing a dashboard with a fixed layout it's difficult to handle the dynamic resizing involved in this approach.  I propose that we add two Boolean flags to control whether we want the user to be able to control the subobject's widgets visibility, and whether we want them visible at first:

   - expandable=False, expand_at_first=True:  Start out expanded; provide no widget to unexpand
   - expandable=False, expand_at_first=False: Start out unexpanded; provide no widget to expand
   - expandable=True,  expand_at_first=True:  Start out expanded, but allow unexpanding
   - expandable=True,  expand_at_first=False: Start out unexpanded, but allow expanding (current default)

This way people could have a fixed layout if they wish, either with or without the ability to edit subobject parameters.

**Comment by philippjfr** [comment]
The names for these options are now:

expand_by_default and toggleable_subobjects

If we want better names we should decide now.

**Comment by jbednar** [comment]
Those are indeed truly terrible names. :-)   How about `subobject_expanded` and `subobject_widget` (or `subobject_button`)?

**Comment by jbednar** [comment]
@philippjfr , Jean-Luc and I just discussed it, and I now propose simply `expand` (for `expand_by_default`) and `expand_widget` (for `toggleable_subobjects`).  These parameters would control not just subobjects, but also things like param.DataFrame that would have bulky representations best not expanded unless actually needed.  Thus it's appropriate for them not to contain the word "subobject".

Could we also maybe have `expand_widget` be None by default?  None would mean that if `expand` is True, then `expand_widget=False` (as when it's expanded initially most people won't need or want a way to unexpand it, particularly as long as there is no responsive layout resizing), and if `expand` is False, then `expand_widget=True` (to give people a way to get access to the subobject parameters).  This way most people would only need to mess with one parameter, namely `expand`.

Also, should `subobject_layout=pn.Column` by default, since the widgets themselves are in a column by default? It's hard to say what default is best, but in the examples I've looked at I generally want pn.Column so that I don't overwrite the items to the right of the widgets.  `subobject_layout` might be best renamed to `expand_layout` to match `expand`...

**Comment by jbednar** [comment]
@philippjfr, can you please weigh in on these names?  I'd like to stop using the old ones in our docs if at all possible...

**Comment by philippjfr** [comment]
Forgot about this one, I'm happy with most of your suggestions, going for a walk and then making a PR for these. I'll have to think about `subobject_layout` in the meantime.

**Comment by philippjfr** [comment]
Decided to adopt all the names except for ``expand_widget`` which I've instead named ``expand_button``.
