### ISSUE TITLE
Add linked plots example

### ISSUE THREAD

**Issue by jbednar** [pyviz/panel#71]
Current Panel examples show off various Panel widgets and various plotting libraries, but we don't currently have a dashboard example where each plot is linked so that selected items in one pane affect each of the others.  A typical example is to "drill down" on some overview plot, expanding selected item(s) in a different plot, and in turn allowing some subset of those values to be displayed as a table.  None of this functionality requires Panel, but it is important to demonstrate that it can be done in Panel, so that one can provide full-featured, deeply interactive dashboards.

**Comment by philippjfr** [comment]
There's a whole user guide and a number of gallery examples now.
