### ISSUE TITLE
FileInput widget and @param.depends interaction

### ISSUE THREAD

**Issue by miguelandrs** [pyviz/panel#711]
I can't seem to figure out the syntax for watching/triggering a function upon someone using a FileInput widget in a Parameterized class.

![image](https://user-images.githubusercontent.com/8538551/66845365-e412ed80-ef3d-11e9-8684-917f02f5559f.png)

I understand that FileInput isn't a param itself, but I looked at the code for it and the value attribute is a generic param.Parameter, so I thought this would work. I also tried just depending on file (@param.depends('file')). 

Appreciate any input or if anyone can point me to appropriate docs. Thanks!

**Comment by philippjfr** [comment]
This is a usage question and should ideally be posted to StackOverflow. It's great you created a detailed example so if you just paste your question and code into StackOverflow I'll be happy to answer.

**Comment by philippjfr** [comment]
Oh, just put the link to the SO question back here so I definitely see it.

**Comment by miguelandrs** [comment]
Sure thing: https://stackoverflow.com/questions/58400769/panel-param-fileinput-widget-and-param-depends-interaction

Thanks!
