### ISSUE TITLE
Select widget pass label instead of value on the javascript side

### ISSUE THREAD

**Issue by xavArtley** [pyviz/panel#718]
I use this code to produce a Select widget with bokeh and panel for comparison
![image](https://user-images.githubusercontent.com/18531147/67151393-fedebc80-f2c5-11e9-8c45-90197983f4b6.png)

But when the value of the Select change I get 
![image](https://user-images.githubusercontent.com/18531147/67151415-41a09480-f2c6-11e9-899b-e9cd97c984b5.png)

However on the python side the value is correct:
![image](https://user-images.githubusercontent.com/18531147/67151430-73196000-f2c6-11e9-86f5-d86227de0e66.png)

**Comment by philippjfr** [comment]
Going to close, the solution in the recent PR seems like the best we can do.
