### ISSUE TITLE
Conflict between Audio and VTKVolume panel

### ISSUE THREAD

**Issue by xavArtley** [pyviz/panel#730]
https://pyviz-dev.github.io/panel/reference/panes/VTKVolume.html#gallery-vtkvolume
![image](https://user-images.githubusercontent.com/18531147/67965035-9535ab00-fc01-11e9-9923-0c1bb48d1288.png)

**Comment by philippjfr** [comment]
Should VTKVolume check for 3D arrays and Audio check for 1D uint16 arrays?

**Comment by xavArtley** [comment]
Seems reasonnable

**Comment by xavArtley** [comment]
Fixed with Audio pane check dtype and ndim #738
