### ISSUE TITLE
DateSlider does not seem to update its value property

### ISSUE THREAD

**Issue by odedbadt** [pyviz/panel#753]
### FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and technical assistance, ask us on [Gitter](https://gitter.im/pyviz/pyviz).

For defects or deficiencies, please provide *ALL OF THE FOLLOWING*:

#### ALL software version info (Panel, bokeh, python, notebook, OS, browser, any other relevant packages)
OS: OSx Mojave 10.14.6
Python: 3.7.3
Browser: FF 69.0.1
Packages:
bokeh                     1.3.4                    py37_0    conda-forge
ipywidgets                7.5.1                      py_0    conda-forge
jupyter                   1.0.0                      py_2    conda-forge
matplotlib                3.1.1                    py37_1    conda-forge
notebook                  6.0.1                    py37_0    conda-forge
pandas                    0.25.3           py37h4f17bb1_0    conda-forge
panel                     0.6.0                         1    conda-forge
python                    3.7.3                h359304d_0

As documented in the dateslider dodumentation (https://panel.pyviz.org/reference/widgets/DateSlider.html), after sliding the slider, the value property of the slider is expected to update. I ran the notebook provided in the example and played around with the slider a bit, checked the value and it did not change. Tried using "date"s instead of "datetime"s and it didn't do the trick. I might be doing something wrong, in that case it might be beneficial to document my pitfall. But it seems that the rest of the examples went pretty smooth (incl. DateRangeSlider)

Code ( as copied from example provided in DateSlider doc):
```
import datetime as dt
import panel as pn

pn.extension()

date_slider = pn.widgets.DateSlider(name='Date Slider', start=dt.datetime(2019, 1, 1), end=dt.datetime(2019, 6, 1), value=dt.datetime(2019, 2, 8))

date_slider
# Play around with the slider
# Check the "value" property
date_slider.value
```

#### Screenshots or screencasts of the bug in action
![Screen Shot 2019-11-07 at 16 06 20](https://user-images.githubusercontent.com/1270681/68395555-96725500-0178-11ea-800e-729f74997588.png)

**Comment by xavArtley** [comment]
Hello
I can't  reproduce:
![image](https://user-images.githubusercontent.com/18531147/68396242-87d46f80-0171-11ea-883d-775becf5488f.png)

**Comment by philippjfr** [comment]
What's your version of Param?

**Comment by odedbadt** [comment]
param                     1.9.2                      py_0    conda-forge

**Comment by odedbadt** [comment]
Short update: on the same machine but with a fresh conda environment everything works as expected. Must be some corruption in my env.
