### ISSUE TITLE
Subobjects overwrite other panes

### ISSUE THREAD

**Issue by jbednar** [pyviz/panel#76]
When a Parameter has a Parameterized as a value, Panel will allow a separate pane to be opened to edit the parameters of that subobject.  However, no space is created for the new pane, causing it to overwrite adjacent items:

```
import param, panel as pn
pn.extension()

class A(param.Parameterized):
    a = param.Number(7, bounds=(0,10))
    b = param.Boolean(True)
    c = param.String("Yes")

x = A(name="A")    

class B(param.Parameterized):
    sub = param.ObjectSelector(x)

y = B(name="B")

pn.Column(pn.Row(y,"https://panel.pyviz.org/_static/logo.png"))
```

![image](https://user-images.githubusercontent.com/1695496/46412655-c2551880-c6e4-11e8-9f36-5b3a366b6820.png)

```
pn.Column(pn.Param(y, subobject_layout=pn.Column),
          "https://panel.pyviz.org/_static/logo.png")
```

![image](https://user-images.githubusercontent.com/1695496/46412678-d3058e80-c6e4-11e8-859b-99ca3d7f3110.png)

Overwriting like this could be appropriate in some cases, but in general it would be better if the other items moved aside to make room for the widgets.  I believe this will have to wait on the Bokeh [layout refactor](https://github.com/bokeh/bokeh/pull/8085).

**Comment by jbednar** [comment]
Also, I think the button should just be labeled "A" above, not "<A A>".  I'm not sure why ObjectSelector sometimes shows a name and sometimes an inappropriate full repr like that.

**Comment by lazarusA** [comment]
So far, I see that the position for widgets is given by default. Is there a way to have an option where we can give coordinate positions (i.e. left, right, etc... )?

**Comment by jbednar** [comment]
You can just make a container for it and put it anywhere you like, then supply that container for `subobject_layout`, so I'm not sure it's worth adding explicit control over the location?

**Comment by lazarusA** [comment]
I was thinking more like a "matplotlib user", there you have the anchor_bbox option, something like that, but if your way works then probably is not necessary.

**Comment by philippjfr** [comment]
Using bokeh and panel dev this now expands correctly.
