### ISSUE TITLE
Styling options not possible for Button widgets

### ISSUE THREAD

**Issue by hyamanieu** [pyviz/panel#773]
When reading the documentation for [button](https://panel.pyviz.org/reference/widgets/Button.html), it looks like we[ can customize the button widget ](https://panel.pyviz.org/user_guide/Customization.html).

It isn't the case. Neither associating a css class with the `css_classes `parameter (1), nor with `style `parameter (2), nor directly using a `text-font-size` parameter (3) -- like with bokeh models -- works to change the font size. I believe it's the case for all widgets, this works only with pane/panel objects like `Column`, `Row`....

Either the documentation should be changed and the Customization sheet shouldn't be mentioned under the Button sheet, or we should be able to change the button style.

1:
```
css = '''
.widget-button {
  font-size: 45pt;
}
'''
panel.extension(raw_css=[css])

button_left = panel.widgets.Button(name='<', 
                                   button_type='primary',
                                   width=150,
                                   height=top_height,
                                   style={'font-size':'45pt'},
                                   css_classes=["widget-button"])
```

2:
```
button_left = panel.widgets.Button(name='<', 
                                   button_type='primary',
                                   width=150,
                                   height=top_height,
                                   style={'font-size':'45pt'})
```
3:
```
button_left = panel.widgets.Button(name='<', 
                                   button_type='primary',
                                   width=150,
                                   height=top_height,
                                   text_font_size="45pt")
```

**Comment by philippjfr** [comment]
This is to do with the way bokeh assigns the classes, in this case the class isn't actually assigned to the button tag but rather to the class containing the button tag. You can change your CSS selector to target the tag:

```
css = '''
.widget-button .bk-btn-group button {
  font-size: 45pt;
}
'''
```

I agree that this should be improved but this issue should ideally be filed with bokeh since we have no control over that in Panel.

**Comment by d16408** [comment]
overzicht styles panel button
