### ISSUE TITLE
Glitch when several bar plots are displayed

### ISSUE THREAD

**Issue by fmaussion** [pyviz/panel#783]
#### Software version

- bokeh 1.4.0
- panel 0.6.4
- hv 1.12.6

run in a jupyter notebook on linux.

#### Description of expected behavior and the observed behavior

When several plots are put together, bar plots have very strange glitches. Here is a simple GIF showing the behavior:

![glitch](https://user-images.githubusercontent.com/10050469/68862067-122a4f80-06ed-11ea-97b9-5cfdb8de9cb4.gif)

When put together, the bar which should be full is not anymore.

If you want to see it live, see our glacier app:  https://bokeh.oggm.org/explorer/glaciers-explorer-panel and select any location on map.

#### Complete, minimal, self-contained example code that reproduces the issue

If the bug is unknown to you, I'll try to put a minimal example together if needed.

**Comment by fmaussion** [comment]
(while we are at it: on [our app](https://bokeh.oggm.org/explorer/glaciers-explorer-panel) you can also see how the logos move in the frame after the first selection has been made. This behavior seems to be random, i.e. another layout might prevent this from happening... Any idea what can cause this?)

**Comment by philippjfr** [comment]
Is this possibly due to shared axes? HoloViews will automatically link axes with the same names and labels.

**Comment by fmaussion** [comment]
> Is this possibly due to shared axes? HoloViews will automatically link axes with the same names and labels.

Sorry I forgot to mention: this worked nicely before I updated my holoviz stack yesterday... Of course I have no clue what versions I had before :roll_eyes: . I can try to make a MWE...

**Comment by fmaussion** [comment]
OK, here is a mwe:

```python
import holoviews as hv, panel as pn, geoviews as gv
import pandas as pd
import numpy as np
hv.extension('bokeh')
pn.extension()

data = pd.DataFrame()
data['CenLon'] = [1, 2, 3]
data['CenLat'] = [1, 2, 3]
data['area'] = [1, 2, 3]
data['vol'] = [10, 20, 30]
data = gv.Points(data, [('CenLon', 'Longitude'), ('CenLat', 'Latitude')],
                       [('area', 'Area'),  ('vol', 'Volume')])
data = gv.Dataset(gv.operation.project_points(data))

size_opts_bar = dict(height=45,  width=250)
opts = dict(size_opts_bar, default_tools=[], toolbar=None, invert_axes=True, show_legend=False, xaxis=None, yaxis=None)

def area(data):   return hv.Bars(('', np.sum(data['area']))).opts(**opts)
def vol(data):    return hv.Bars(('', np.sum(data['vol']))).opts(**opts)

static_area = area(data).options(alpha=0.1)
static_vol = vol(data).options(alpha=0.1)
```

Which results in:

![Selection_084](https://user-images.githubusercontent.com/10050469/68871079-2f1a4f00-06fc-11ea-9e5e-c96f2daeadc8.png)

**Comment by philippjfr** [comment]
I would expect those to normalize like that unless `axiswise=True` or `shared_axes=False` is set. That said there has been a regression in HoloViews where axiswise=True is not respected properly.

**Comment by philippjfr** [comment]
The fix that's required here is in HoloViews so I'll close.

**Comment by fmaussion** [comment]
@philippjfr  apologies, I think we should reopen this, it seems to be a panel issue. 

My description of the true issue was misleading. What I'm reporting here are the glitches we see on the bars in the interactive app, here with latest panel:

![glitch_pn_new](https://user-images.githubusercontent.com/10050469/69238300-ebaa5f80-0b97-11ea-8552-d44383ad387a.gif)

I've tracked down the latest panel version which works for us: it is panel 0.6.2. See the app working with this version:

![glitch_pn_old](https://user-images.githubusercontent.com/10050469/69238339-08469780-0b98-11ea-85e4-17bacdce9885.gif)

**Comment by philippjfr** [comment]
Did you try setting axiswise as a HoloViews option or linked_axes=False on the Panel HoloViews pane?

**Comment by fmaussion** [comment]
I just tried to set `axiswise=False` or `axiswise=True` to the holoviews bar objects without success (I installed holoviews from master for this, which had the other problem of making datashaded glaciers disappear on the map).

I'm sorry, but I don't know what you mean with "linked_axes=False on the Panel HoloViews pane" :disappointed: 

The code for the app is here:  https://github.com/OGGM/world-glacier-explorer/blob/master/app.ipynb (search for `vol_opts`)

Served on MyBinder with panel pinned to 0.6.2: https://mybinder.org/v2/gh/OGGM/world-glacier-explorer/master?urlpath=panel/app

Served on MyBinder with panel unpinned: https://mybinder.org/v2/gh/OGGM/world-glacier-explorer/panel?urlpath=panel/app

(the panel version has another strange influence on how datashader is rendered btw...)

**Comment by ahuang11** [comment]
I think `pn.Pane(layout, linked_axes=False)` like inhttps://github.com/holoviz/panel/issues/798#issuecomment-556714494

**Comment by fmaussion** [comment]
OK! We didn't use Panes, so this is what I had to change:

```python
bars = pn.Row(pn.Column(pn.layout.Spacer(height=8), 
                        pn.Pane(dyn_count1), pn.layout.Spacer(height=0), gl_num, pn.layout.Spacer(height=1), 
                        pn.Pane(dyn_count2), pn.layout.Spacer(height=0), area_bar, pn.layout.Spacer(height=1), 
                        pn.Pane(dyn_count3), pn.layout.Spacer(height=0), vol_bar, 
                        pn.layout.Spacer(height=15)), 
              sealevelrise)
```


to

```python
bars = pn.Row(pn.Column(pn.layout.Spacer(height=8), 
                        pn.Pane(dyn_count1), pn.layout.Spacer(height=0), pn.Pane(gl_num, linked_axes=False), pn.layout.Spacer(height=1), 
                        pn.Pane(dyn_count2), pn.layout.Spacer(height=0), pn.Pane(area_bar, linked_axes=False), pn.layout.Spacer(height=1), 
                        pn.Pane(dyn_count3), pn.layout.Spacer(height=0), pn.Pane(vol_bar, linked_axes=False), 
                        pn.layout.Spacer(height=15)), 
              pn.Pane(sealevelrise, linked_axes=False))
```

But isn't this still a bug? It seems odd to have to set this explicitly for it not to glitch?

**Comment by fmaussion** [comment]
> Super cool looking dashboard by the way!

Thanks! @philippjfr did the hard work, and @zschirmeister added some data and the bar plots. We are now going to advertise it since it works nicely ;-)

**Comment by philippjfr** [comment]
The expected behaviour is for multiple HoloViews plots in a layout to be normalized together if their dimensions match. This was implemented for Panel only recently which is why it appears like a regression. The bug is that the axiswise option in HoloViews has regressed in the last release which I'm about to fix in a new release.

**Comment by philippjfr** [comment]
Great you got it working in any case! It does look great!
