### ISSUE TITLE
collapsible=True / expandable=True for pn.Column

### ISSUE THREAD

**Issue by ahuang11** [pyviz/panel#792]
`pn.Columns(*items, collapsible=True)`

Or maybe a new class
`pn.Expand()`?

Similar to:
https://github.com/pydata/xarray/pull/3425
![image](https://user-images.githubusercontent.com/15331990/68958068-fb3d3900-0790-11ea-8d6c-72e85d474809.png)

**Comment by philippjfr** [comment]
Adding it to Columns is unlikely and adding a collapsible layout is covered by https://github.com/pyviz/panel/issues/561
