### ISSUE TITLE
Why are my panes spaced so far apart?

### ISSUE THREAD

**Issue by jbednar** [pyviz/panel#93]
In #21, the code:

```
import param, panel as pp, numpy as np
from panel import pane
pp.extension()

pp.Row("<i>string</i>",
          pane.Pane("<b>Pane</b>"), 
          pane.HTML("<u>HTML</u>"), 
          pane.Str( "<i>Str</i>"),
          pane.Str(np.zeros((5,3)), height=80))
```

is shown generating the output:

![image](https://user-images.githubusercontent.com/1695496/45097843-5d100680-b0e9-11e8-87a0-6bf9c4ff7197.png)

However, if I check out the panel commit corresponding to that revision (655b90214c4acda379f318783cba5377983d5c19), I get the same widely spaced output that I am getting for that code on current Panel master:

![image](https://user-images.githubusercontent.com/1695496/46775989-515ac580-cccf-11e8-9649-581a5c39e703.png)

Can anyone think of why these results would be different, for what I think is the same panel code? What I'd like is something in the middle, i.e. with a parameter for inter-pane spacing that I could set to 20px or so, but otherwise like the old behavior.

**Comment by philippjfr** [comment]
I'd probably try going back to the commit before that PR and then try to figure out the structure of the generated bokeh models. My initial guess is that something about the WidgetBox each Div is in has changed.

**Comment by jbednar** [comment]
Unless I'm confused, I don't think the spacing change has anything to do with that PR itself, because the example above was done *with* the code in the PR.  I.e., it seems like something outside of the Panel code is what's changed, as that same Panel code used to behave differently than it does now.

**Comment by philippjfr** [comment]
>Unless I'm confused, I don't think the spacing change has anything to do with that PR itself, because the example above was done with the code in the PR.

The PR was rebased towards the end before merging, so that image was probably generated before that was done, in which case you might have to go a few commits back from there.

**Comment by jbednar** [comment]
Ah, that would explain it.  I'll see if I can narrow it down.

**Comment by jbednar** [comment]
Ok, I was able to narrow it down.  It was tricky, because the API changed so many times, but here's some code that runs across versions:

```
from IPython.display import HTML as ipyHTML
h = ipyHTML("<u>HTML</u>")

import param, panel as pn, numpy as np
try:
    from panel.pane import Pane
    from panel.pane import HTML
except:
    try:
        from panel.panes import Pane
        from panel.panes import HTMLPane as HTML
    except:
        try:
            from panel.panes import Pane
            from panel.panes import HTML     
        except:
            from panel.panels import Panel as Pane
            from panel.panels import HTMLPanel as HTML

pn.extension()

pn.Row(HTML(h), HTML(h), HTML(h))
```

The output is what I'd expect, in commit 3cea6f2ebf27d86147dff9a7ff00500b5cf27db5 (Sep 4, "Wrap raw bokeh model widgets in WidgetBox (#22)"):

![image](https://user-images.githubusercontent.com/1695496/46827172-92012000-cd5d-11e8-8c15-01a65f7a9528.png)

And it all gets spaced out in the next commit (Sep 5 , "Always wrap Div and widgets in WidgetBox (#25)")
![image](https://user-images.githubusercontent.com/1695496/46827200-aa713a80-cd5d-11e8-86cf-836e80671c5f.png)

**Comment by jbednar** [comment]
The notes for the PR say that it's about making sizing more consistent, but to me it looks like wrapping things in WidgetBoxes is messing things up...

**Comment by philippjfr** [comment]
Having trouble seeing how either of those commits could be the cause since they apply only to the Bokeh pane, but I'll keep looking.

**Comment by philippjfr** [comment]
Nevermind I see the issue.
