### ISSUE TITLE
Add panel entry point

### ISSUE THREAD

**Issue by jbednar** [pyviz/panel#99]
Passing along a suggestion that I think is a good one: so that Panel users won't be affected if we eventually do split out the parts of Bokeh that Panel uses, we should add an entry point for launching servers like `panel serve file.py`.  For now that would just delegate to `bokeh serve file.py`, but we could then change that to whatever the underlying Bokeh infrastructure becomes, which could even be part of Panel itself.

**Comment by philippjfr** [comment]
This was implemented.
